In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
delay_df = pd.read_csv("D:/Jai - NSS/bna-airline-delay-patterns/bna-delay-cause/Airline_Delay_Cause.csv")
delay_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 571 non-null    int64
 1   month                571 non-null    int64
 2   carrier              571 non-null    object
 3   carrier_name         571 non-null    object
 4   airport              571 non-null    object
 5   airport_name         571 non-null    object
 6   arr_flights          571 non-null    float64
 7   arr_del15            571 non-null    float64
 8   carrier_ct           571 non-null    float64
 9   weather_ct           571 non-null    float64
 10  nas_ct               571 non-null    float64
 11  security_ct          571 non-null    float64
 12  late_aircraft_ct     571 non-null    float64
 13  arr_cancelled        571 non-null    float64
 14  arr_diverted         571 non-null    float64
 15  arr_delay            571 non-null    float64
 16  carrier_delay        571 non-null    float64
 17  weather_delay        571 non-null    float64
 18  nas_delay            571 non-null    float64
 19  security_delay       571 non-null    float64
 20  late_aircraft_delay  571 non-null    float64
dtypes: float64(15), int64(2), object(4)
memory usage: 93.8+ KB

In [3]:
delay_df.head(1)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,NK,Spirit Airlines,BNA,"Nashville, TN: Nashville International",187.0,40.0,11.81,0.08,...,0.63,7.62,2.0,0.0,2447.0,607.0,10.0,1208.0,25.0,597.0

In [33]:
delay_df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,NK,Spirit Airlines,BNA,"Nashville, TN: Nashville International",187.0,40.0,11.81,0.08,...,0.63,7.62,2.0,0.0,2447.0,607.0,10.0,1208.0,25.0,597.0
1,2024,12,OH,PSA Airlines Inc.,BNA,"Nashville, TN: Nashville International",299.0,87.0,32.26,1.87,...,0.00,31.28,2.0,0.0,5646.0,1615.0,218.0,944.0,0.0,2869.0
2,2024,12,OO,SkyWest Airlines Inc.,BNA,"Nashville, TN: Nashville International",345.0,95.0,48.79,17.40,...,0.00,14.34,0.0,0.0,7396.0,3433.0,1800.0,915.0,0.0,1248.0
4,2024,12,UA,United Air Lines Network,BNA,"Nashville, TN: Nashville International",448.0,92.0,36.54,0.92,...,0.00,31.78,2.0,0.0,4694.0,1520.0,132.0,750.0,0.0,2292.0
5,2024,12,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4301.0,803.0,228.66,6.43,...,6.16,457.44,8.0,1.0,44612.0,11030.0,559.0,4025.0,419.0,28579.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,2022,1,OO,SkyWest Airlines Inc.,BNA,"Nashville, TN: Nashville International",363.0,74.0,56.00,5.00,...,0.00,13.00,41.0,1.0,4887.0,3480.0,218.0,0.0,0.0,1189.0
567,2022,1,UA,United Air Lines Network,BNA,"Nashville, TN: Nashville International",215.0,40.0,26.37,0.00,...,0.00,5.32,33.0,0.0,2590.0,1938.0,0.0,302.0,0.0,350.0
568,2022,1,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3311.0,517.0,192.47,9.16,...,0.55,241.37,269.0,5.0,28401.0,9411.0,728.0,3197.0,23.0,15042.0
569,2022,1,YV,Mesa Airlines Inc.,BNA,"Nashville, TN: Nashville International",53.0,6.0,5.00,0.00,...,0.00,0.00,17.0,0.0,363.0,317.0,0.0,46.0,0.0,0.0
570,2022,1,YX,Republic Airline,BNA,"Nashville, TN: Nashville International",677.0,151.0,49.69,7.33,...,0.00,39.06,68.0,1.0,8502.0,3281.0,579.0,1984.0,0.0,2658.0

In [4]:
delay_df['carrier_name'].value_counts()
##Look at three years of data. remove those that are niche airports and will definitely skew the data set. 36 shows that the flights appear at least once in the with

carrier_name
Spirit Airlines                              36
American Airlines Network                    36
Envoy Air                                    36
Allegiant Air                                36
Frontier Airlines                            36
Delta Air Lines Network                      36
JetBlue Airways                              36
PSA Airlines Inc.                            36
Alaska Airlines Network                      36
Endeavor Air Inc.                            36
Republic Airline                             36
Mesa Airlines Inc.                           36
Southwest Airlines                           36
United Air Lines Network                     36
SkyWest Airlines Inc.                        36
GoJet Airlines LLC d/b/a United Express      14
Piedmont Airlines                            10
Air Wisconsin Airlines Corp                   4
Commutair Aka Champlain Enterprises, Inc.     2
CommuteAir LLC dba CommuteAir                 1
Name: count, dtype: int64

In [5]:
niche_airlines = ['GoJet Airlines LLC d/b/a United Express','Piedmont Airlines','Air Wisconsin Airlines Corp','Commutair Aka Champlain Enterprises, Inc.','CommuteAir LLC dba CommuteAir']

delay_df = delay_df[~delay_df['carrier_name'].isin(niche_airlines)]
delay_df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,NK,Spirit Airlines,BNA,"Nashville, TN: Nashville International",187.0,40.0,11.81,0.08,...,0.63,7.62,2.0,0.0,2447.0,607.0,10.0,1208.0,25.0,597.0
1,2024,12,OH,PSA Airlines Inc.,BNA,"Nashville, TN: Nashville International",299.0,87.0,32.26,1.87,...,0.00,31.28,2.0,0.0,5646.0,1615.0,218.0,944.0,0.0,2869.0
2,2024,12,OO,SkyWest Airlines Inc.,BNA,"Nashville, TN: Nashville International",345.0,95.0,48.79,17.40,...,0.00,14.34,0.0,0.0,7396.0,3433.0,1800.0,915.0,0.0,1248.0
4,2024,12,UA,United Air Lines Network,BNA,"Nashville, TN: Nashville International",448.0,92.0,36.54,0.92,...,0.00,31.78,2.0,0.0,4694.0,1520.0,132.0,750.0,0.0,2292.0
5,2024,12,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4301.0,803.0,228.66,6.43,...,6.16,457.44,8.0,1.0,44612.0,11030.0,559.0,4025.0,419.0,28579.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,2022,1,OO,SkyWest Airlines Inc.,BNA,"Nashville, TN: Nashville International",363.0,74.0,56.00,5.00,...,0.00,13.00,41.0,1.0,4887.0,3480.0,218.0,0.0,0.0,1189.0
567,2022,1,UA,United Air Lines Network,BNA,"Nashville, TN: Nashville International",215.0,40.0,26.37,0.00,...,0.00,5.32,33.0,0.0,2590.0,1938.0,0.0,302.0,0.0,350.0
568,2022,1,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3311.0,517.0,192.47,9.16,...,0.55,241.37,269.0,5.0,28401.0,9411.0,728.0,3197.0,23.0,15042.0
569,2022,1,YV,Mesa Airlines Inc.,BNA,"Nashville, TN: Nashville International",53.0,6.0,5.00,0.00,...,0.00,0.00,17.0,0.0,363.0,317.0,0.0,46.0,0.0,0.0
570,2022,1,YX,Republic Airline,BNA,"Nashville, TN: Nashville International",677.0,151.0,49.69,7.33,...,0.00,39.06,68.0,1.0,8502.0,3281.0,579.0,1984.0,0.0,2658.0

In [6]:
delay_df[['arr_del15','arr_flights','carrier_ct','weather_delay','weather_ct','arr_delay']]

     arr_del15  arr_flights  carrier_ct  weather_delay  weather_ct  arr_delay
0         40.0        187.0       11.81           10.0        0.08     2447.0
1         87.0        299.0       32.26          218.0        1.87     5646.0
2         95.0        345.0       48.79         1800.0       17.40     7396.0
4         92.0        448.0       36.54          132.0        0.92     4694.0
5        803.0       4301.0      228.66          559.0        6.43    44612.0
..         ...          ...         ...            ...         ...        ...
566       74.0        363.0       56.00          218.0        5.00     4887.0
567       40.0        215.0       26.37            0.0        0.00     2590.0
568      517.0       3311.0      192.47          728.0        9.16    28401.0
569        6.0         53.0        5.00            0.0        0.00      363.0
570      151.0        677.0       49.69          579.0        7.33     8502.0

[540 rows x 6 columns]

# Delayed Rates by carrier name from 2022-2024

In [7]:
carrier_performance_agg = delay_df.groupby('carrier_name').agg(totalflights = ('arr_flights', 'sum'),
                                                             delayedflights = ('arr_del15','sum'),
                                                              delayedmin = ('arr_delay','sum'))
carrier_performance_agg

                           totalflights  delayedflights  delayedmin
carrier_name
Alaska Airlines Network          2743.0           576.0     22878.0
Allegiant Air                    9574.0          2534.0    205334.0
American Airlines Network       23804.0          6574.0    483191.0
Delta Air Lines Network         24034.0          3672.0    221160.0
Endeavor Air Inc.                4280.0           751.0     49621.0
Envoy Air                        7548.0          1536.0     87801.0
Frontier Airlines                2781.0           706.0     46101.0
JetBlue Airways                  5771.0          1697.0    127220.0
Mesa Airlines Inc.               1990.0           340.0     23333.0
PSA Airlines Inc.                7127.0          1340.0     87106.0
Republic Airline                16358.0          2402.0    146035.0
SkyWest Airlines Inc.           11110.0          2383.0    193616.0
Southwest Airlines             142793.0         26679.0   1413458.0
Spirit Airlines                  9516.0          2354.0    155549.0
United Air Lines Network        16235.0          3383.0    232303.0

In [8]:
carrier_performance_agg['delayed_rates_percent'] = ((carrier_performance_agg['delayedflights']/carrier_performance_agg['totalflights'])*100).round(2)
carrier_performance_agg['avg_min_overall'] = (carrier_performance_agg['delayedmin']/carrier_performance_agg['delayedflights'])
carrier_performance_agg = carrier_performance_agg.sort_values(by = 'delayed_rates_percent', ascending = False)
carrier_performance_agg = carrier_performance_agg.sort_values(by = ['totalflights','delayed_rates_percent'], ascending = [False, False])

In [9]:
carrier_performance_agg = carrier_performance_agg.rename(columns = {'totalflights': 'Total Flights Overall',
                                                                    'carrier_name': 'Airline',
                                                                    'delayedflights': '# of Overall Delayed Flights',
                                                                    'delayed_rates_percent': 'Flights Delayed Overall (%)', 
                                                                    'avg_min_overall':'Overall Average Flight Delay (Minutes)',
                                                                   'delayedmin':'Overall Count of Minutes Delayed'})
carrier_performance_agg

,Total Flights Overall,# of Overall Delayed Flights,Overall Count of Minutes Delayed,Flights Delayed Overall (%),Overall Average Flight Delay (Minutes)
carrier_name,,,,,
Southwest Airlines,142793.0,26679.0,1413458.0,18.68,52.980172
Delta Air Lines Network,24034.0,3672.0,221160.0,15.28,60.228758
American Airlines Network,23804.0,6574.0,483191.0,27.62,73.500304
Republic Airline,16358.0,2402.0,146035.0,14.68,60.797252
United Air Lines Network,16235.0,3383.0,232303.0,20.84,68.667751
SkyWest Airlines Inc.,11110.0,2383.0,193616.0,21.45,81.248846
Allegiant Air,9574.0,2534.0,205334.0,26.47,81.031571
Spirit Airlines,9516.0,2354.0,155549.0,24.74,66.078590
Envoy Air,7548.0,1536.0,87801.0,20.35,57.162109
PSA Airlines Inc.,7127.0,1340.0,87106.0,18.80,65.004478
JetBlue Airways,5771.0,1697.0,127220.0,29.41,74.967590
Endeavor Air Inc.,4280.0,751.0,49621.0,17.55,66.073236
Frontier Airlines,2781.0,706.0,46101.0,25.39,65.298867
Alaska Airlines Network,2743.0,576.0,22878.0,21.00,39.718750
Mesa Airlines Inc.,1990.0,340.0,23333.0,17.09,68.626471

In [10]:
carrier_performance_agg['Flights Delayed Overall (%)'].mean()

21.29

# avg delay of flights in minutes overall

In [11]:
avg_delay_grouped = delay_df.groupby('carrier_name')['arr_delay'].mean().reset_index()
avg_delay_grouped

                 carrier_name     arr_delay
0     Alaska Airlines Network    635.500000
1               Allegiant Air   5703.722222
2   American Airlines Network  13421.972222
3     Delta Air Lines Network   6143.333333
4           Endeavor Air Inc.   1378.361111
5                   Envoy Air   2438.916667
6           Frontier Airlines   1280.583333
7             JetBlue Airways   3533.888889
8          Mesa Airlines Inc.    648.138889
9           PSA Airlines Inc.   2419.611111
10           Republic Airline   4056.527778
11      SkyWest Airlines Inc.   5378.222222
12         Southwest Airlines  39262.722222
13            Spirit Airlines   4320.805556
14   United Air Lines Network   6452.861111

In [12]:
delay_df[delay_df['arr_delay'] >= 75452].head(2)
## arr_del15 = weather_ct + nas_ct + security_ct + late_aircraft_ct + arr_cancelled + arr_diverted

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
119,2024,5,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4302.0,1171.0,278.08,33.72,...,4.24,629.7,14.0,21.0,75452.0,16167.0,3090.0,11443.0,239.0,44513.0

In [13]:
southwest_df = delay_df[delay_df['carrier_name'] == 'Southwest Airlines']

In [14]:
southwest_df[['carrier_name','arr_del15','carrier_ct','weather_ct','nas_ct','security_ct','late_aircraft_ct']].sample(2)
## the arrival_del15 is total count of flight delays by carrier,weather,nas,security, and just late

,carrier_name,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct
327,Southwest Airlines,897.0,270.60,6.31,138.57,8.45,473.07
297,Southwest Airlines,1081.0,277.35,30.23,182.95,5.58,584.89

In [15]:
southwest_df[['arr_delay','carrier_delay','weather_delay','nas_delay','security_delay','late_aircraft_delay']].sample(2)
##the arr_del is total count of flight delays by carrier,weather,nas,security, and just late by minutes per month.

,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
119,75452.0,16167.0,3090.0,11443.0,239.0,44513.0
568,28401.0,9411.0,728.0,3197.0,23.0,15042.0

# Delay of flights per month by carrier

In [16]:
delayed_months =(delay_df.groupby(['carrier_name', 'month'])[['arr_del15', 'arr_flights', 'arr_delay']].sum().reset_index())
delayed_months['percent_delayed_m'] = (delayed_months['arr_del15'] / delayed_months['arr_flights']).round(4)*100
delayed_months = delayed_months[['percent_delayed_m','carrier_name', 'month','arr_del15', 'arr_flights', 'arr_delay']]

# Delayed flights per year by carrier

In [17]:
delayed_year =(delay_df.groupby(['carrier_name', 'year'])[['arr_del15', 'arr_flights', 'arr_delay']].sum().reset_index())
delayed_year['percent_delayed_y'] = (delayed_year['arr_del15'] / delayed_year['arr_flights']).round(4)*100
delayed_year = delayed_year[['percent_delayed_y','carrier_name', 'year','arr_del15', 'arr_flights', 'arr_delay']]
delayed_year

,percent_delayed_y,carrier_name,year,arr_del15,arr_flights,arr_delay
0,19.83,Alaska Airlines Network,2022,138.0,696.0,6120.0
1,24.22,Alaska Airlines Network,2023,202.0,834.0,7079.0
2,19.46,Alaska Airlines Network,2024,236.0,1213.0,9679.0
3,37.19,Allegiant Air,2022,899.0,2417.0,63519.0
4,26.73,Allegiant Air,2023,1104.0,4130.0,85523.0
5,17.54,Allegiant Air,2024,531.0,3027.0,56292.0
6,24.81,American Airlines Network,2022,1801.0,7259.0,122720.0
7,26.49,American Airlines Network,2023,2151.0,8119.0,159114.0
8,31.12,American Airlines Network,2024,2622.0,8426.0,201357.0
9,15.07,Delta Air Lines Network,2022,1118.0,7417.0,66128.0
10,16.04,Delta Air Lines Network,2023,1320.0,8228.0,81013.0
11,14.71,Delta Air Lines Network,2024,1234.0,8389.0,74019.0
12,18.31,Endeavor Air Inc.,2022,396.0,2163.0,24682.0
13,15.84,Endeavor Air Inc.,2023,147.0,928.0,9534.0
14,17.49,Endeavor Air Inc.,2024,208.0,1189.0,15405.0
15,18.32,Envoy Air,2022,387.0,2113.0,21924.0
16,20.81,Envoy Air,2023,603.0,2898.0,33863.0
17,21.52,Envoy Air,2024,546.0,2537.0,32014.0
18,27.37,Frontier Airlines,2022,248.0,906.0,15661.0
19,26.73,Frontier Airlines,2023,297.0,1111.0,18185.0
20,21.07,Frontier Airlines,2024,161.0,764.0,12255.0
21,32.65,JetBlue Airways,2022,717.0,2196.0,51535.0
22,31.35,JetBlue Airways,2023,696.0,2220.0,55361.0
23,20.96,JetBlue Airways,2024,284.0,1355.0,20324.0
24,15.01,Mesa Airlines Inc.,2022,107.0,713.0,6072.0
25,21.08,Mesa Airlines Inc.,2023,160.0,759.0,11061.0
26,14.09,Mesa Airlines Inc.,2024,73.0,518.0,6200.0
27,21.27,PSA Airlines Inc.,2022,400.0,1881.0,24684.0
28,15.90,PSA Airlines Inc.,2023,452.0,2843.0,28841.0
29,20.31,PSA Airlines Inc.,2024,488.0,2403.0,33581.0
30,19.47,Republic Airline,2022,1195.0,6139.0,73895.0
31,11.54,Republic Airline,2023,519.0,4497.0,30428.0
32,12.02,Republic Airline,2024,688.0,5722.0,41712.0
33,19.61,SkyWest Airlines Inc.,2022,833.0,4247.0,57269.0
34,21.29,SkyWest Airlines Inc.,2023,581.0,2729.0,48150.0
35,23.44,SkyWest Airlines Inc.,2024,969.0,4134.0,88197.0
36,20.00,Southwest Airlines,2022,8704.0,43529.0,468168.0
37,18.43,Southwest Airlines,2023,8896.0,48264.0,453500.0
38,17.80,Southwest Airlines,2024,9079.0,51000.0,491790.0
39,23.26,Spirit Airlines,2022,570.0,2451.0,34835.0
40,28.02,Spirit Airlines,2023,914.0,3262.0,60095.0
41,22.88,Spirit Airlines,2024,870.0,3803.0,60619.0
42,20.08,United Air Lines Network,2022,713.0,3551.0,52803.0
43,22.48,United Air Lines Network,2023,1447.0,6436.0,95605.0
44,19.57,United Air Lines Network,2024,1223.0,6248.0,83895.0

# average minutes of flights by minute by carrier per month

In [18]:
avg_min_months =(delay_df.groupby(['carrier_name', 'month'])[['arr_flights','arr_del15', 'arr_delay']].sum().reset_index())
avg_min_months['avg_min_m'] = (avg_min_months['arr_delay'] / avg_min_months['arr_del15'])
avg_min_months = avg_min_months[['avg_min_m', 'carrier_name','month', 'arr_flights','arr_del15', 'arr_delay']]
avg_min_months

,avg_min_m,carrier_name,month,arr_flights,arr_del15,arr_delay
0,45.461538,Alaska Airlines Network,1,151.0,39.0,1773.0
1,39.600000,Alaska Airlines Network,2,159.0,25.0,990.0
2,48.722222,Alaska Airlines Network,3,212.0,36.0,1754.0
3,32.750000,Alaska Airlines Network,4,234.0,56.0,1834.0
4,37.507937,Alaska Airlines Network,5,244.0,63.0,2363.0
...,...,...,...,...,...,...
175,71.824451,United Air Lines Network,8,1457.0,319.0,22912.0
176,68.347639,United Air Lines Network,9,1517.0,233.0,15925.0
177,55.069307,United Air Lines Network,10,1581.0,202.0,11124.0
178,63.702326,United Air Lines Network,11,1381.0,215.0,13696.0
179,59.240175,United Air Lines Network,12,1242.0,229.0,13566.0

In [19]:
avg_min_years =(delay_df.groupby(['carrier_name', 'year'])[['arr_flights','arr_del15', 'arr_delay']].sum().reset_index())
avg_min_years['avg_min_y'] = (avg_min_years['arr_delay'] / avg_min_years['arr_del15'])
avg_min_years = avg_min_years[['avg_min_y','carrier_name','year', 'arr_flights','arr_del15', 'arr_delay']]
avg_min_years

,avg_min_y,carrier_name,year,arr_flights,arr_del15,arr_delay
0,44.347826,Alaska Airlines Network,2022,696.0,138.0,6120.0
1,35.044554,Alaska Airlines Network,2023,834.0,202.0,7079.0
2,41.012712,Alaska Airlines Network,2024,1213.0,236.0,9679.0
3,70.655172,Allegiant Air,2022,2417.0,899.0,63519.0
4,77.466486,Allegiant Air,2023,4130.0,1104.0,85523.0
5,106.011299,Allegiant Air,2024,3027.0,531.0,56292.0
6,68.139922,American Airlines Network,2022,7259.0,1801.0,122720.0
7,73.972106,American Airlines Network,2023,8119.0,2151.0,159114.0
8,76.795195,American Airlines Network,2024,8426.0,2622.0,201357.0
9,59.148479,Delta Air Lines Network,2022,7417.0,1118.0,66128.0
10,61.373485,Delta Air Lines Network,2023,8228.0,1320.0,81013.0
11,59.982982,Delta Air Lines Network,2024,8389.0,1234.0,74019.0
12,62.328283,Endeavor Air Inc.,2022,2163.0,396.0,24682.0
13,64.857143,Endeavor Air Inc.,2023,928.0,147.0,9534.0
14,74.062500,Endeavor Air Inc.,2024,1189.0,208.0,15405.0
15,56.651163,Envoy Air,2022,2113.0,387.0,21924.0
16,56.157546,Envoy Air,2023,2898.0,603.0,33863.0
17,58.633700,Envoy Air,2024,2537.0,546.0,32014.0
18,63.149194,Frontier Airlines,2022,906.0,248.0,15661.0
19,61.228956,Frontier Airlines,2023,1111.0,297.0,18185.0
20,76.118012,Frontier Airlines,2024,764.0,161.0,12255.0
21,71.875872,JetBlue Airways,2022,2196.0,717.0,51535.0
22,79.541667,JetBlue Airways,2023,2220.0,696.0,55361.0
23,71.563380,JetBlue Airways,2024,1355.0,284.0,20324.0
24,56.747664,Mesa Airlines Inc.,2022,713.0,107.0,6072.0
25,69.131250,Mesa Airlines Inc.,2023,759.0,160.0,11061.0
26,84.931507,Mesa Airlines Inc.,2024,518.0,73.0,6200.0
27,61.710000,PSA Airlines Inc.,2022,1881.0,400.0,24684.0
28,63.807522,PSA Airlines Inc.,2023,2843.0,452.0,28841.0
29,68.813525,PSA Airlines Inc.,2024,2403.0,488.0,33581.0
30,61.836820,Republic Airline,2022,6139.0,1195.0,73895.0
31,58.628131,Republic Airline,2023,4497.0,519.0,30428.0
32,60.627907,Republic Airline,2024,5722.0,688.0,41712.0
33,68.750300,SkyWest Airlines Inc.,2022,4247.0,833.0,57269.0
34,82.874355,SkyWest Airlines Inc.,2023,2729.0,581.0,48150.0
35,91.018576,SkyWest Airlines Inc.,2024,4134.0,969.0,88197.0
36,53.787684,Southwest Airlines,2022,43529.0,8704.0,468168.0
37,50.977968,Southwest Airlines,2023,48264.0,8896.0,453500.0
38,54.167860,Southwest Airlines,2024,51000.0,9079.0,491790.0
39,61.114035,Spirit Airlines,2022,2451.0,570.0,34835.0
40,65.749453,Spirit Airlines,2023,3262.0,914.0,60095.0
41,69.677011,Spirit Airlines,2024,3803.0,870.0,60619.0
42,74.057504,United Air Lines Network,2022,3551.0,713.0,52803.0
43,66.071182,United Air Lines Network,2023,6436.0,1447.0,95605.0
44,68.597711,United Air Lines Network,2024,6248.0,1223.0,83895.0

In [20]:
print(avg_min_months['avg_min_m'].max())
print(avg_min_years['avg_min_y'].max())

104.94711538461539
106.01129943502825

# DataFrame for years

In [21]:
yearly_df = pd.merge(avg_min_years, delayed_year, on=['year', 'carrier_name','arr_flights','arr_del15', 'arr_delay'], how='inner')
yearly_df = yearly_df.sort_values(by = ['carrier_name','year'], ascending = [True, True])
yearly_df

,avg_min_y,carrier_name,year,arr_flights,arr_del15,arr_delay,percent_delayed_y
0,44.347826,Alaska Airlines Network,2022,696.0,138.0,6120.0,19.83
1,35.044554,Alaska Airlines Network,2023,834.0,202.0,7079.0,24.22
2,41.012712,Alaska Airlines Network,2024,1213.0,236.0,9679.0,19.46
3,70.655172,Allegiant Air,2022,2417.0,899.0,63519.0,37.19
4,77.466486,Allegiant Air,2023,4130.0,1104.0,85523.0,26.73
5,106.011299,Allegiant Air,2024,3027.0,531.0,56292.0,17.54
6,68.139922,American Airlines Network,2022,7259.0,1801.0,122720.0,24.81
7,73.972106,American Airlines Network,2023,8119.0,2151.0,159114.0,26.49
8,76.795195,American Airlines Network,2024,8426.0,2622.0,201357.0,31.12
9,59.148479,Delta Air Lines Network,2022,7417.0,1118.0,66128.0,15.07
10,61.373485,Delta Air Lines Network,2023,8228.0,1320.0,81013.0,16.04
11,59.982982,Delta Air Lines Network,2024,8389.0,1234.0,74019.0,14.71
12,62.328283,Endeavor Air Inc.,2022,2163.0,396.0,24682.0,18.31
13,64.857143,Endeavor Air Inc.,2023,928.0,147.0,9534.0,15.84
14,74.062500,Endeavor Air Inc.,2024,1189.0,208.0,15405.0,17.49
15,56.651163,Envoy Air,2022,2113.0,387.0,21924.0,18.32
16,56.157546,Envoy Air,2023,2898.0,603.0,33863.0,20.81
17,58.633700,Envoy Air,2024,2537.0,546.0,32014.0,21.52
18,63.149194,Frontier Airlines,2022,906.0,248.0,15661.0,27.37
19,61.228956,Frontier Airlines,2023,1111.0,297.0,18185.0,26.73
20,76.118012,Frontier Airlines,2024,764.0,161.0,12255.0,21.07
21,71.875872,JetBlue Airways,2022,2196.0,717.0,51535.0,32.65
22,79.541667,JetBlue Airways,2023,2220.0,696.0,55361.0,31.35
23,71.563380,JetBlue Airways,2024,1355.0,284.0,20324.0,20.96
24,56.747664,Mesa Airlines Inc.,2022,713.0,107.0,6072.0,15.01
25,69.131250,Mesa Airlines Inc.,2023,759.0,160.0,11061.0,21.08
26,84.931507,Mesa Airlines Inc.,2024,518.0,73.0,6200.0,14.09
27,61.710000,PSA Airlines Inc.,2022,1881.0,400.0,24684.0,21.27
28,63.807522,PSA Airlines Inc.,2023,2843.0,452.0,28841.0,15.90
29,68.813525,PSA Airlines Inc.,2024,2403.0,488.0,33581.0,20.31
30,61.836820,Republic Airline,2022,6139.0,1195.0,73895.0,19.47
31,58.628131,Republic Airline,2023,4497.0,519.0,30428.0,11.54
32,60.627907,Republic Airline,2024,5722.0,688.0,41712.0,12.02
33,68.750300,SkyWest Airlines Inc.,2022,4247.0,833.0,57269.0,19.61
34,82.874355,SkyWest Airlines Inc.,2023,2729.0,581.0,48150.0,21.29
35,91.018576,SkyWest Airlines Inc.,2024,4134.0,969.0,88197.0,23.44
36,53.787684,Southwest Airlines,2022,43529.0,8704.0,468168.0,20.00
37,50.977968,Southwest Airlines,2023,48264.0,8896.0,453500.0,18.43
38,54.167860,Southwest Airlines,2024,51000.0,9079.0,491790.0,17.80
39,61.114035,Spirit Airlines,2022,2451.0,570.0,34835.0,23.26
40,65.749453,Spirit Airlines,2023,3262.0,914.0,60095.0,28.02
41,69.677011,Spirit Airlines,2024,3803.0,870.0,60619.0,22.88
42,74.057504,United Air Lines Network,2022,3551.0,713.0,52803.0,20.08
43,66.071182,United Air Lines Network,2023,6436.0,1447.0,95605.0,22.48
44,68.597711,United Air Lines Network,2024,6248.0,1223.0,83895.0,19.57

In [22]:
yearly_df = yearly_df[['carrier_name', 'year', 'avg_min_y', 'percent_delayed_y','arr_del15','arr_flights','arr_delay']]
yearly_df = yearly_df.rename(columns={
    'carrier_name': 'Airline',
    'year' : 'Year',
    'avg_min_y': 'Yearly Average Flight Delay (Minutes)',
    'percent_delayed_y': 'Flights Delayed Yearly (%)',
    'arr_flights': 'Total Flights Yearly Overall',
    'arr_del15': '# of Yearly Overall Delayed Flights',
    'arr_delay': 'Overall count of delayed minutes (Yearly)'})
yearly_df = yearly_df[['Airline',
                         'Year',
                         'Total Flights Yearly Overall',
                         '# of Yearly Overall Delayed Flights',
                         'Overall count of delayed minutes (Yearly)',
                         'Flights Delayed Yearly (%)',
                         'Yearly Average Flight Delay (Minutes)']]
yearly_df

,Airline,Year,Total Flights Yearly Overall,# of Yearly Overall Delayed Flights,Overall count of delayed minutes (Yearly),Flights Delayed Yearly (%),Yearly Average Flight Delay (Minutes)
0,Alaska Airlines Network,2022,696.0,138.0,6120.0,19.83,44.347826
1,Alaska Airlines Network,2023,834.0,202.0,7079.0,24.22,35.044554
2,Alaska Airlines Network,2024,1213.0,236.0,9679.0,19.46,41.012712
3,Allegiant Air,2022,2417.0,899.0,63519.0,37.19,70.655172
4,Allegiant Air,2023,4130.0,1104.0,85523.0,26.73,77.466486
5,Allegiant Air,2024,3027.0,531.0,56292.0,17.54,106.011299
6,American Airlines Network,2022,7259.0,1801.0,122720.0,24.81,68.139922
7,American Airlines Network,2023,8119.0,2151.0,159114.0,26.49,73.972106
8,American Airlines Network,2024,8426.0,2622.0,201357.0,31.12,76.795195
9,Delta Air Lines Network,2022,7417.0,1118.0,66128.0,15.07,59.148479
10,Delta Air Lines Network,2023,8228.0,1320.0,81013.0,16.04,61.373485
11,Delta Air Lines Network,2024,8389.0,1234.0,74019.0,14.71,59.982982
12,Endeavor Air Inc.,2022,2163.0,396.0,24682.0,18.31,62.328283
13,Endeavor Air Inc.,2023,928.0,147.0,9534.0,15.84,64.857143
14,Endeavor Air Inc.,2024,1189.0,208.0,15405.0,17.49,74.062500
15,Envoy Air,2022,2113.0,387.0,21924.0,18.32,56.651163
16,Envoy Air,2023,2898.0,603.0,33863.0,20.81,56.157546
17,Envoy Air,2024,2537.0,546.0,32014.0,21.52,58.633700
18,Frontier Airlines,2022,906.0,248.0,15661.0,27.37,63.149194
19,Frontier Airlines,2023,1111.0,297.0,18185.0,26.73,61.228956
20,Frontier Airlines,2024,764.0,161.0,12255.0,21.07,76.118012
21,JetBlue Airways,2022,2196.0,717.0,51535.0,32.65,71.875872
22,JetBlue Airways,2023,2220.0,696.0,55361.0,31.35,79.541667
23,JetBlue Airways,2024,1355.0,284.0,20324.0,20.96,71.563380
24,Mesa Airlines Inc.,2022,713.0,107.0,6072.0,15.01,56.747664
25,Mesa Airlines Inc.,2023,759.0,160.0,11061.0,21.08,69.131250
26,Mesa Airlines Inc.,2024,518.0,73.0,6200.0,14.09,84.931507
27,PSA Airlines Inc.,2022,1881.0,400.0,24684.0,21.27,61.710000
28,PSA Airlines Inc.,2023,2843.0,452.0,28841.0,15.90,63.807522
29,PSA Airlines Inc.,2024,2403.0,488.0,33581.0,20.31,68.813525
30,Republic Airline,2022,6139.0,1195.0,73895.0,19.47,61.836820
31,Republic Airline,2023,4497.0,519.0,30428.0,11.54,58.628131
32,Republic Airline,2024,5722.0,688.0,41712.0,12.02,60.627907
33,SkyWest Airlines Inc.,2022,4247.0,833.0,57269.0,19.61,68.750300
34,SkyWest Airlines Inc.,2023,2729.0,581.0,48150.0,21.29,82.874355
35,SkyWest Airlines Inc.,2024,4134.0,969.0,88197.0,23.44,91.018576
36,Southwest Airlines,2022,43529.0,8704.0,468168.0,20.00,53.787684
37,Southwest Airlines,2023,48264.0,8896.0,453500.0,18.43,50.977968
38,Southwest Airlines,2024,51000.0,9079.0,491790.0,17.80,54.167860
39,Spirit Airlines,2022,2451.0,570.0,34835.0,23.26,61.114035
40,Spirit Airlines,2023,3262.0,914.0,60095.0,28.02,65.749453
41,Spirit Airlines,2024,3803.0,870.0,60619.0,22.88,69.677011
42,United Air Lines Network,2022,3551.0,713.0,52803.0,20.08,74.057504
43,United Air Lines Network,2023,6436.0,1447.0,95605.0,22.48,66.071182
44,United Air Lines Network,2024,6248.0,1223.0,83895.0,19.57,68.597711

# Dataframe for months

In [23]:
monthly_df = pd.merge(avg_min_months, delayed_months, on=['month', 'carrier_name','arr_flights','arr_del15', 'arr_delay'], how='inner')
monthly_df = monthly_df.sort_values(by = ['carrier_name','month'], ascending = [True, True])
monthly_df

,avg_min_m,carrier_name,month,arr_flights,arr_del15,arr_delay,percent_delayed_m
0,45.461538,Alaska Airlines Network,1,151.0,39.0,1773.0,25.83
1,39.600000,Alaska Airlines Network,2,159.0,25.0,990.0,15.72
2,48.722222,Alaska Airlines Network,3,212.0,36.0,1754.0,16.98
3,32.750000,Alaska Airlines Network,4,234.0,56.0,1834.0,23.93
4,37.507937,Alaska Airlines Network,5,244.0,63.0,2363.0,25.82
...,...,...,...,...,...,...,...
175,71.824451,United Air Lines Network,8,1457.0,319.0,22912.0,21.89
176,68.347639,United Air Lines Network,9,1517.0,233.0,15925.0,15.36
177,55.069307,United Air Lines Network,10,1581.0,202.0,11124.0,12.78
178,63.702326,United Air Lines Network,11,1381.0,215.0,13696.0,15.57
179,59.240175,United Air Lines Network,12,1242.0,229.0,13566.0,18.44

In [24]:
monthly_df = monthly_df[['carrier_name', 'month', 'avg_min_m', 'percent_delayed_m','arr_del15','arr_flights','arr_delay']]
monthly_df = monthly_df.rename(columns={
    'carrier_name': 'Airline',
    'month' : 'Month',
    'avg_min_m': 'Monthly Average Flight Delay (Minutes)',
    'percent_delayed_m': 'Flights Delayed Monthly (%)',
    'arr_flights':'Total Flights Monthly Overall',
    'arr_del15': '# of Monthly Overall Delayed Flights',
    'arr_delay': 'Overall count of delayed minutes (monthly)'})
monthly_df.columns.to_list()

['Airline',
 'Month',
 'Monthly Average Flight Delay (Minutes)',
 'Flights Delayed Monthly (%)',
 '# of Monthly Overall Delayed Flights',
 'Total Flights Monthly Overall',
 'Overall count of delayed minutes (monthly)']

In [25]:
monthly_df = monthly_df[['Airline',
                         'Month',
                         'Total Flights Monthly Overall',
                         '# of Monthly Overall Delayed Flights',
                         'Overall count of delayed minutes (monthly)',
                         'Flights Delayed Monthly (%)',
                         'Monthly Average Flight Delay (Minutes)']]
monthly_df

,Airline,Month,Total Flights Monthly Overall,# of Monthly Overall Delayed Flights,Overall count of delayed minutes (monthly),Flights Delayed Monthly (%),Monthly Average Flight Delay (Minutes)
0,Alaska Airlines Network,1,151.0,39.0,1773.0,25.83,45.461538
1,Alaska Airlines Network,2,159.0,25.0,990.0,15.72,39.600000
2,Alaska Airlines Network,3,212.0,36.0,1754.0,16.98,48.722222
3,Alaska Airlines Network,4,234.0,56.0,1834.0,23.93,32.750000
4,Alaska Airlines Network,5,244.0,63.0,2363.0,25.82,37.507937
...,...,...,...,...,...,...,...
175,United Air Lines Network,8,1457.0,319.0,22912.0,21.89,71.824451
176,United Air Lines Network,9,1517.0,233.0,15925.0,15.36,68.347639
177,United Air Lines Network,10,1581.0,202.0,11124.0,12.78,55.069307
178,United Air Lines Network,11,1381.0,215.0,13696.0,15.57,63.702326
179,United Air Lines Network,12,1242.0,229.0,13566.0,18.44,59.240175

# DataFrame for all three years

In [26]:
carrier_performance_agg = carrier_performance_agg.rename(columns={'carrier_name': 'Airline'})
carrier_performance_agg

,Total Flights Overall,# of Overall Delayed Flights,Overall Count of Minutes Delayed,Flights Delayed Overall (%),Overall Average Flight Delay (Minutes)
carrier_name,,,,,
Southwest Airlines,142793.0,26679.0,1413458.0,18.68,52.980172
Delta Air Lines Network,24034.0,3672.0,221160.0,15.28,60.228758
American Airlines Network,23804.0,6574.0,483191.0,27.62,73.500304
Republic Airline,16358.0,2402.0,146035.0,14.68,60.797252
United Air Lines Network,16235.0,3383.0,232303.0,20.84,68.667751
SkyWest Airlines Inc.,11110.0,2383.0,193616.0,21.45,81.248846
Allegiant Air,9574.0,2534.0,205334.0,26.47,81.031571
Spirit Airlines,9516.0,2354.0,155549.0,24.74,66.078590
Envoy Air,7548.0,1536.0,87801.0,20.35,57.162109
PSA Airlines Inc.,7127.0,1340.0,87106.0,18.80,65.004478
JetBlue Airways,5771.0,1697.0,127220.0,29.41,74.967590
Endeavor Air Inc.,4280.0,751.0,49621.0,17.55,66.073236
Frontier Airlines,2781.0,706.0,46101.0,25.39,65.298867
Alaska Airlines Network,2743.0,576.0,22878.0,21.00,39.718750
Mesa Airlines Inc.,1990.0,340.0,23333.0,17.09,68.626471

In [27]:
southwest_df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
5,2024,12,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4301.0,803.0,228.66,6.43,...,6.16,457.44,8.0,1.0,44612.0,11030.0,559.0,4025.0,419.0,28579.0
30,2024,11,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4237.0,479.0,147.17,2.39,...,3.00,265.05,10.0,0.0,23146.0,8064.0,143.0,2085.0,136.0,12718.0
36,2024,10,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4620.0,516.0,179.69,1.27,...,3.03,240.50,51.0,12.0,22899.0,8018.0,62.0,3024.0,58.0,11737.0
62,2024,9,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4145.0,498.0,141.64,5.10,...,1.41,252.95,21.0,20.0,22331.0,6639.0,224.0,3379.0,38.0,12051.0
78,2024,8,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4403.0,763.0,223.04,20.45,...,1.50,426.45,39.0,3.0,42486.0,12099.0,1443.0,4269.0,83.0,24592.0
94,2024,7,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4691.0,1197.0,323.61,32.10,...,5.66,661.59,17.0,13.0,66721.0,16005.0,2353.0,8941.0,164.0,39258.0
105,2024,6,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4503.0,976.0,286.08,14.83,...,2.64,547.62,13.0,12.0,53754.0,14752.0,951.0,5198.0,130.0,32723.0
119,2024,5,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4302.0,1171.0,278.08,33.72,...,4.24,629.70,14.0,21.0,75452.0,16167.0,3090.0,11443.0,239.0,44513.0
142,2024,4,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4177.0,711.0,212.94,9.86,...,3.83,382.92,10.0,4.0,37176.0,10509.0,787.0,3913.0,153.0,21814.0
148,2024,3,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4204.0,756.0,209.65,6.94,...,1.67,439.84,27.0,3.0,41901.0,11281.0,523.0,4278.0,56.0,25763.0
172,2024,2,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3536.0,388.0,132.08,2.54,...,4.91,184.15,8.0,2.0,18320.0,5834.0,167.0,2405.0,348.0,9566.0
184,2024,1,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3881.0,821.0,250.76,8.53,...,2.03,390.99,203.0,4.0,42992.0,11892.0,651.0,7484.0,139.0,22826.0
204,2023,12,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4333.0,758.0,246.38,8.58,...,5.59,368.20,30.0,11.0,36225.0,10465.0,641.0,4930.0,204.0,19985.0
218,2023,11,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4202.0,581.0,204.37,0.21,...,1.93,277.54,5.0,1.0,22576.0,8327.0,7.0,2896.0,44.0,11302.0
234,2023,10,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4549.0,754.0,237.68,4.43,...,2.00,402.06,8.0,1.0,34419.0,11998.0,301.0,3856.0,101.0,18163.0
249,2023,9,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3955.0,598.0,156.12,17.30,...,5.13,324.24,18.0,9.0,29645.0,7226.0,1711.0,3352.0,184.0,17172.0
264,2023,8,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4116.0,677.0,188.13,16.82,...,3.96,356.10,31.0,8.0,33431.0,8935.0,1384.0,4666.0,249.0,18197.0
280,2023,7,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4177.0,1136.0,293.85,37.93,...,6.81,622.88,29.0,9.0,68491.0,16615.0,3395.0,8468.0,307.0,39706.0
297,2023,6,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3947.0,1081.0,277.35,30.23,...,5.58,584.89,20.0,20.0,60937.0,14321.0,2163.0,10235.0,193.0,34025.0
312,2023,5,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4016.0,705.0,217.08,18.50,...,0.00,367.04,23.0,10.0,33215.0,8907.0,2003.0,6237.0,0.0,16068.0
327,2023,4,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3820.0,897.0,270.60,6.31,...,8.45,473.07,20.0,7.0,47366.0,14500.0,551.0,5817.0,753.0,25745.0
344,2023,3,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3937.0,723.0,221.11,6.07,...,3.85,392.32,59.0,23.0,33648.0,9652.0,569.0,4357.0,302.0,18768.0
360,2023,2,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3423.0,377.0,143.07,1.02,...,0.84,175.99,61.0,1.0,16450.0,6589.0,140.0,1818.0,15.0,7888.0
376,2023,1,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3789.0,609.0,216.81,6.65,...,2.86,293.74,114.0,1.0,37097.0,14372.0,489.0,3621.0,75.0,18540.0
392,2022,12,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3842.0,724.0,270.71,7.43,...,3.71,354.99,635.0,9.0,50832.0,18239.0,605.0,5500.0,306.0,26182.0
409,2022,11,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3681.0,540.0,195.65,5.78,...,2.84,259.39,22.0,1.0,26238.0,9855.0,315.0,3273.0,87.0,12708.0
424,2022,10,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4012.0,623.0,268.26,3.99,...,2.73,290.26,29.0,2.0,28703.0,11996.0,365.0,2071.0,109.0,14162.0
441,2022,9,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3845.0,726.0,284.20,15.23,...,1.03,357.98,61.0,4.0,34851.0,12751.0,1099.0,2668.0,36.0,18297.0
457,2022,8,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3842.0,1019.0,363.80,18.90,...,4.31,532.88,67.0,20.0,62479.0,20342.0,1530.0,4654.0,270.0,35683.0
473,2022,7,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3812.0,912.0,344.83,17.89,...,2.64,465.54,26.0,2.0,47863.0,16106.0,1313.0,3425.0,116.0,26903.0
476,2022,6,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3611.0,783.0,289.34,13.81,...,0.61,415.14,24.0,5.0,42140.0,13290.0,1349.0,3700.0,28.0,23773.0
504,2022,5,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3648.0,652.0,227.39,8.29,...,2.58,337.33,12.0,3.0,30176.0,9593.0,696.0,3236.0,185.0,16466.0
521,2022,4,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3454.0,841.0,302.86,13.59,...,1.56,393.01,58.0,4.0,44291.0,13394.0,1172.0,7324.0,45.0,22356.0
538,2022,3,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3351.0,813.0,294.87,7.61,...,2.86,403.84,75.0,1.0,45749.0,14709.0,820.0,4922.0,152.0,25146.0
553,2022,2,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3120.0,554.0,230.77,7.84,...,1.52,218.15,111.0,5.0,26445.0,11211.0,446.0,3407.0,49.0,11332.0
568,2022,1,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3311.0,517.0,192.47,9.16,...,0.55,241.37,269.0,5.0,28401.0,9411.0,728.0,3197.0,23.0,15042.0

In [28]:
delay_df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,12,NK,Spirit Airlines,BNA,"Nashville, TN: Nashville International",187.0,40.0,11.81,0.08,...,0.63,7.62,2.0,0.0,2447.0,607.0,10.0,1208.0,25.0,597.0
1,2024,12,OH,PSA Airlines Inc.,BNA,"Nashville, TN: Nashville International",299.0,87.0,32.26,1.87,...,0.00,31.28,2.0,0.0,5646.0,1615.0,218.0,944.0,0.0,2869.0
2,2024,12,OO,SkyWest Airlines Inc.,BNA,"Nashville, TN: Nashville International",345.0,95.0,48.79,17.40,...,0.00,14.34,0.0,0.0,7396.0,3433.0,1800.0,915.0,0.0,1248.0
4,2024,12,UA,United Air Lines Network,BNA,"Nashville, TN: Nashville International",448.0,92.0,36.54,0.92,...,0.00,31.78,2.0,0.0,4694.0,1520.0,132.0,750.0,0.0,2292.0
5,2024,12,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",4301.0,803.0,228.66,6.43,...,6.16,457.44,8.0,1.0,44612.0,11030.0,559.0,4025.0,419.0,28579.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,2022,1,OO,SkyWest Airlines Inc.,BNA,"Nashville, TN: Nashville International",363.0,74.0,56.00,5.00,...,0.00,13.00,41.0,1.0,4887.0,3480.0,218.0,0.0,0.0,1189.0
567,2022,1,UA,United Air Lines Network,BNA,"Nashville, TN: Nashville International",215.0,40.0,26.37,0.00,...,0.00,5.32,33.0,0.0,2590.0,1938.0,0.0,302.0,0.0,350.0
568,2022,1,WN,Southwest Airlines,BNA,"Nashville, TN: Nashville International",3311.0,517.0,192.47,9.16,...,0.55,241.37,269.0,5.0,28401.0,9411.0,728.0,3197.0,23.0,15042.0
569,2022,1,YV,Mesa Airlines Inc.,BNA,"Nashville, TN: Nashville International",53.0,6.0,5.00,0.00,...,0.00,0.00,17.0,0.0,363.0,317.0,0.0,46.0,0.0,0.0
570,2022,1,YX,Republic Airline,BNA,"Nashville, TN: Nashville International",677.0,151.0,49.69,7.33,...,0.00,39.06,68.0,1.0,8502.0,3281.0,579.0,1984.0,0.0,2658.0

# Large data Frame with Delay count percentage

In [29]:
delay_df.columns.tolist()

['year',
 'month',
 'carrier',
 'carrier_name',
 'airport',
 'airport_name',
 'arr_flights',
 'arr_del15',
 'carrier_ct',
 'weather_ct',
 'nas_ct',
 'security_ct',
 'late_aircraft_ct',
 'arr_cancelled',
 'arr_diverted',
 'arr_delay',
 'carrier_delay',
 'weather_delay',
 'nas_delay',
 'security_delay',
 'late_aircraft_delay']

In [30]:
group_cols = [
    'year',
    'month',
    'carrier',
    'carrier_name',
    'airport',
    'airport_name']
agg_cols = [
    'arr_flights',
    'arr_del15',
    'carrier_ct',
    'weather_ct',
    'nas_ct',
    'security_ct',
    'late_aircraft_ct',
    'arr_cancelled',
    'arr_diverted',
    'arr_delay',
    'carrier_delay',
    'weather_delay',
    'nas_delay',
    'security_delay',
    'late_aircraft_delay']

performance_df = delay_df.groupby(group_cols).agg({col: 'sum' for col in agg_cols}).reset_index()

In [31]:
performance_df['flights_delayed_pct'] = ((performance_df['arr_del15'] / performance_df['arr_flights']).fillna(0).round(2) * 100)
performance_df['flights_delayed_pct'] = performance_df['flights_delayed_pct'].fillna(0)

In [32]:
delay_cause = ['carrier_ct','weather_ct','nas_ct','security_ct','late_aircraft_ct']

for delay in delay_cause:
    performance_df[delay + '_pct'] = ((performance_df[cause]/performance_df['arr_del15'])*100).round(2)
    performance_df[delay + '_pct'] = performance_df[delay + '_pct'].fillna(0)

NameError: name 'cause' is not defined

In [ ]:
performance_df

In [ ]:
performance_df['cancel_rate'] = performance_df['arr_cancelled'] / performance_df['arr_flights'].round(4).fillna(0)
performance_df['divert_rate'] = performance_df['arr_diverted'] / performance_df['arr_flights'].round(4).fillna(0)

In [ ]:
performance_df