In [1]:
import pandas as pd
import numpy as np
import requests
import zipfile
from pathlib import Path
import pandas as pd
from io import BytesIO, StringIO
import time
import os
from datetime import datetime, date, time

In [2]:
folder_path = "D:/Jai - NSS/bna-airline-delay-patterns/bna-delay-cause-files"

# List to store all DataFrames
all_dfs = []

for file_name in os.listdir(folder_path):
    if file_name.endswith(".zip"):
        zip_path = os.path.join(folder_path, file_name)
        
        with zipfile.ZipFile(zip_path, 'r') as zip_file:
            for inner_file in zip_file.namelist():
                # Check if the inner file is a CSV
                if inner_file.endswith(".csv"):
                    with zip_file.open(inner_file) as f:
                        # Read bytes and decode to string
                        data = f.read().decode('utf-8')
                        
                        # Load CSV into a DataFrame
                        df = pd.read_csv(StringIO(data))
                        all_dfs.append(df)

# Combine all DataFrames into one
combined_df = pd.concat(all_dfs, ignore_index=True)
print(combined_df.head())
#https://www.geeksforgeeks.org/python/working-zip-files-python/
##little side note 'utf-8' is how python reads bytes to string. If you do not add 'utf-8' it will read all the data raw. There are other like 'latin-1', 'iso-8859-1' ,'utf-16' If you try to decode a file with the wrong encoding, Python will raise a UnicodeDecodeError

   YEAR  QUARTER  MONTH  DAY_OF_MONTH  DAY_OF_WEEK               FL_DATE  \
0  2024        1      1             1            1  1/1/2024 12:00:00 AM
1  2024        1      1             1            1  1/1/2024 12:00:00 AM
2  2024        1      1             1            1  1/1/2024 12:00:00 AM
3  2024        1      1             1            1  1/1/2024 12:00:00 AM
4  2024        1      1             1            1  1/1/2024 12:00:00 AM

  BRANDED_CODE_SHARE ORIGIN DEST  CRS_DEP_TIME  ...  CANCELLED  \
0                 AA    BNA  CLT           537  ...        0.0
1                 AA    BNA  CLT           732  ...        0.0
2                 AA    BNA  CLT           943  ...        0.0
3                 AA    BNA  CLT          1927  ...        0.0
4                 AA    BNA  DFW           501  ...        0.0

   CANCELLATION_CODE DIVERTED  FLIGHTS  DISTANCE  CARRIER_DELAY WEATHER_DELAY  \
0                NaN      0.0      1.0     328.0            NaN           NaN
1                NaN      0.0      1.0     328.0            NaN           NaN
2                NaN      0.0      1.0     328.0            NaN           NaN
3                NaN      0.0      1.0     328.0            NaN           NaN
4                NaN      0.0      1.0     631.0            NaN           NaN

   NAS_DELAY SECURITY_DELAY  LATE_AIRCRAFT_DELAY
0        NaN            NaN                  NaN
1        NaN            NaN                  NaN
2        NaN            NaN                  NaN
3        NaN            NaN                  NaN
4        NaN            NaN                  NaN

[5 rows x 27 columns]

In [3]:
combined_df

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,BRANDED_CODE_SHARE,ORIGIN,DEST,CRS_DEP_TIME,...,CANCELLED,CANCELLATION_CODE,DIVERTED,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2024,1,1,1,1,1/1/2024 12:00:00 AM,AA,BNA,CLT,537,...,0.0,NaN,0.0,1.0,328.0,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,1,1,1/1/2024 12:00:00 AM,AA,BNA,CLT,732,...,0.0,NaN,0.0,1.0,328.0,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,1,1,1/1/2024 12:00:00 AM,AA,BNA,CLT,943,...,0.0,NaN,0.0,1.0,328.0,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,1,1,1/1/2024 12:00:00 AM,AA,BNA,CLT,1927,...,0.0,NaN,0.0,1.0,328.0,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,1,1,1/1/2024 12:00:00 AM,AA,BNA,DFW,501,...,0.0,NaN,0.0,1.0,631.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887288,2022,4,12,31,6,12/31/2022 12:00:00 AM,WN,TPA,BNA,1030,...,0.0,NaN,0.0,1.0,612.0,NaN,NaN,NaN,NaN,NaN
887289,2022,4,12,31,6,12/31/2022 12:00:00 AM,WN,TPA,BNA,1255,...,0.0,NaN,0.0,1.0,612.0,NaN,NaN,NaN,NaN,NaN
887290,2022,4,12,31,6,12/31/2022 12:00:00 AM,WN,TPA,BNA,1750,...,0.0,NaN,0.0,1.0,612.0,NaN,NaN,NaN,NaN,NaN
887291,2022,4,12,31,6,12/31/2022 12:00:00 AM,WN,TPA,BNA,1910,...,0.0,NaN,0.0,1.0,612.0,4.0,0.0,0.0,0.0,19.0
887292,2022,4,12,31,6,12/31/2022 12:00:00 AM,WN,TPA,MEM,1550,...,0.0,NaN,0.0,1.0,655.0,29.0,0.0,0.0,0.0,77.0

In [4]:
combined_df.columns = combined_df.columns.str.lower().str.strip()

In [5]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887293 entries, 0 to 887292
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 887293 non-null  int64
 1   quarter              887293 non-null  int64
 2   month                887293 non-null  int64
 3   day_of_month         887293 non-null  int64
 4   day_of_week          887293 non-null  int64
 5   fl_date              887293 non-null  object
 6   branded_code_share   887293 non-null  object
 7   origin               887293 non-null  object
 8   dest                 887293 non-null  object
 9   crs_dep_time         887293 non-null  int64
 10  dep_delay_new        872711 non-null  float64
 11  dep_del15            872711 non-null  float64
 12  dep_time_blk         887293 non-null  object
 13  crs_arr_time         887293 non-null  int64
 14  arr_delay_new        870506 non-null  float64
 15  arr_del15            870506 non-null  float64
 16  arr_time_blk         887293 non-null  object
 17  cancelled            887293 non-null  float64
 18  cancellation_code    14941 non-null   object
 19  diverted             887293 non-null  float64
 20  flights              887293 non-null  float64
 21  distance             887293 non-null  float64
 22  carrier_delay        172257 non-null  float64
 23  weather_delay        172257 non-null  float64
 24  nas_delay            172257 non-null  float64
 25  security_delay       172257 non-null  float64
 26  late_aircraft_delay  172257 non-null  float64
dtypes: float64(13), int64(7), object(7)
memory usage: 182.8+ MB

In [6]:
combined_df.fl_date.nunique() ## There was originally 1066 instead of 1095. 3*365 is 1095. I do not know why there are 1096

1096

In [7]:
combined_df['fl_date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 887293 entries, 0 to 887292
Series name: fl_date
Non-Null Count   Dtype
--------------   -----
887293 non-null  object
dtypes: object(1)
memory usage: 6.8+ MB

### 3*365 = 1095 days. There is an extra day that needs to be looked at
#### There is a leap year in 02/29/2024. Like the niche airlines let remove the niche day. It only happens every 4 years.

In [8]:
combined_df['fl_date'] = pd.to_datetime(combined_df['fl_date'], errors='coerce')
combined_df = combined_df[combined_df['fl_date'] != '2024-02-29']
combined_df['fl_date'] = combined_df['fl_date'].dt.date

C:\Users\Cajun\AppData\Local\Temp\ipykernel_21300\2202483181.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_df['fl_date'] = pd.to_datetime(combined_df['fl_date'], errors='coerce')
C:\Users\Cajun\AppData\Local\Temp\ipykernel_21300\2202483181.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_df['fl_date'] = combined_df['fl_date'].dt.date

In [9]:
bna_df = combined_df[(combined_df['origin'] == 'BNA')]
bna_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285863 entries, 0 to 887175
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 285863 non-null  int64
 1   quarter              285863 non-null  int64
 2   month                285863 non-null  int64
 3   day_of_month         285863 non-null  int64
 4   day_of_week          285863 non-null  int64
 5   fl_date              285863 non-null  object
 6   branded_code_share   285863 non-null  object
 7   origin               285863 non-null  object
 8   dest                 285863 non-null  object
 9   crs_dep_time         285863 non-null  int64
 10  dep_delay_new        280768 non-null  float64
 11  dep_del15            280768 non-null  float64
 12  dep_time_blk         285863 non-null  object
 13  crs_arr_time         285863 non-null  int64
 14  arr_delay_new        280046 non-null  float64
 15  arr_del15            280046 non-null  float64
 16  arr_time_blk         285863 non-null  object
 17  cancelled            285863 non-null  float64
 18  cancellation_code    5181 non-null    object
 19  diverted             285863 non-null  float64
 20  flights              285863 non-null  float64
 21  distance             285863 non-null  float64
 22  carrier_delay        55446 non-null   float64
 23  weather_delay        55446 non-null   float64
 24  nas_delay            55446 non-null   float64
 25  security_delay       55446 non-null   float64
 26  late_aircraft_delay  55446 non-null   float64
dtypes: float64(13), int64(7), object(7)
memory usage: 61.1+ MB

In [10]:
bna_df = bna_df.drop_duplicates()
bna_df['fl_date'].nunique() ## Leap Year adds a day. There was a leap year in 2024

1095

In [11]:
missing_data = bna_df[bna_df['month'] == 2]
missing_data.fl_date.nunique() 
print(f'Formerly there were 85 days. Now there are {missing_data.fl_date.nunique()} days')

Formerly there were 85 days. Now there are 84 days

### Need to confirm if the date ranges are missing one day

In [12]:
full_range = pd.date_range(start = bna_df['fl_date'].min(), end = bna_df['fl_date'].max())
full_range
## https://pandas.pydata.org/docs/reference/api/pandas.date_range.html

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25',
               '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29',
               '2024-12-30', '2024-12-31'],
              dtype='datetime64[ns]', length=1096, freq='D')

In [13]:
existing_dates = pd.to_datetime(bna_df['fl_date'].unique())
existing_dates

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=1095, freq=None)

In [14]:
missing_dates = full_range.difference(existing_dates) ##The .difference() method returns a set that contains the difference between two sets.
print(f"Total missing days: {len(missing_dates)}") ## There were 30 days missing from the month of June. I was able to extract and place it back. Now it shows 0.

Total missing days: 1

In [15]:
bna_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 285863 entries, 0 to 887175
Data columns (total 27 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 285863 non-null  int64
 1   quarter              285863 non-null  int64
 2   month                285863 non-null  int64
 3   day_of_month         285863 non-null  int64
 4   day_of_week          285863 non-null  int64
 5   fl_date              285863 non-null  object
 6   branded_code_share   285863 non-null  object
 7   origin               285863 non-null  object
 8   dest                 285863 non-null  object
 9   crs_dep_time         285863 non-null  int64
 10  dep_delay_new        280768 non-null  float64
 11  dep_del15            280768 non-null  float64
 12  dep_time_blk         285863 non-null  object
 13  crs_arr_time         285863 non-null  int64
 14  arr_delay_new        280046 non-null  float64
 15  arr_del15            280046 non-null  float64
 16  arr_time_blk         285863 non-null  object
 17  cancelled            285863 non-null  float64
 18  cancellation_code    5181 non-null    object
 19  diverted             285863 non-null  float64
 20  flights              285863 non-null  float64
 21  distance             285863 non-null  float64
 22  carrier_delay        55446 non-null   float64
 23  weather_delay        55446 non-null   float64
 24  nas_delay            55446 non-null   float64
 25  security_delay       55446 non-null   float64
 26  late_aircraft_delay  55446 non-null   float64
dtypes: float64(13), int64(7), object(7)
memory usage: 61.1+ MB

# Let's look at the airlines that share a code

In [16]:
bna_df['branded_code_share'].unique() ## Codeshare are for  branded codeshare partners are regional airline affiliates that operate flights marketed and sold by larger "mainline" carriers under the mainline carriers' brand names.

array(['AA', 'AA_CODESHARE', 'AS', 'B6', 'DL', 'DL_CODESHARE', 'F9', 'G4',
       'NK', 'UA', 'UA_CODESHARE', 'WN'], dtype=object)

In [17]:
bna_df = bna_df[~bna_df['branded_code_share'].str.contains('_CODESHARE')]

In [18]:
bna_df['branded_code_share'].unique()

array(['AA', 'AS', 'B6', 'DL', 'F9', 'G4', 'NK', 'UA', 'WN'], dtype=object)

#### There are two common ways to assign seasons to months:
####  1. Using a dictionary to map months to seasons
####  2. Creating a user-defined function
#### Here’s an example using a dictionary:
#### season_map = {1: "Winter", 2: "Winter",3: "Spring", 4: "Spring", 5: "Spring", 6: "Summer", 7: "Summer", 8: "Summer", 9: "Fall", 10: "Fall", 11: "Fall", 12: "Winter"}

#### The map() function can then be used to apply this mapping to a pandas Series. It applies a given function or mapping to each element of an iterable (like a list or Series) and returns a new mapped object.
#### For more details, see: https://www.geeksforgeeks.org/python/python-map-function/

In [19]:
def season_map(season):
    if season <=2:
        return 'winter'
    elif 3 <= season <=5:
        return 'spring'
    elif 6 <= season <= 8:
        return 'summer'
    elif 9 <= season <= 11:
        return 'fall'
    else:
        return 'winter'


bna_df['season'] = bna_df['month'].map(season_map)
bna_df.sample(5)

,year,quarter,month,day_of_month,day_of_week,fl_date,branded_code_share,origin,dest,crs_dep_time,...,cancellation_code,diverted,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,season
444738,2023,2,6,13,2,2023-06-13,WN,BNA,ATL,1555,...,NaN,0.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,summer
793465,2022,3,8,31,3,2022-08-31,WN,BNA,ATL,930,...,NaN,0.0,1.0,214.0,NaN,NaN,NaN,NaN,NaN,summer
835942,2022,4,10,25,2,2022-10-25,AA,BNA,PHL,645,...,NaN,0.0,1.0,675.0,NaN,NaN,NaN,NaN,NaN,fall
797273,2022,3,9,5,1,2022-09-05,WN,BNA,DEN,1250,...,NaN,0.0,1.0,1014.0,NaN,NaN,NaN,NaN,NaN,fall
383929,2023,1,3,31,5,2023-03-31,B6,BNA,LGA,639,...,NaN,0.0,1.0,764.0,NaN,NaN,NaN,NaN,NaN,spring

In [20]:
bna_df['arr_time_blk'].unique()

array(['0800-0859', '0900-0959', '1200-1259', '2100-2159', '0700-0759',
       '1000-1059', '1300-1359', '1500-1559', '1700-1759', '1900-1959',
       '1100-1159', '2000-2059', '1600-1659', '1400-1459', '2200-2259',
       '0001-0559', '2300-2359', '1800-1859', '0600-0659'], dtype=object)

In [21]:
##Morning: Generally considered to start around 6 AM and end around 12 PM (noon).
##Early Morning: 5 AM to 8 AM.
##Late Morning: 11 AM to 12 PM.
##Afternoon: 12 PM (noon) to 6 PM.
##Early Afternoon: 1 PM to 3 PM.
##Late Afternoon: 4 PM to 5 PM.
##Evening: 6 PM to 12 AM (midnight).
##Night: 12 AM (midnight) to 6 AM.


time_map = {0: 'Night',
            1: 'Night',
            2: 'Night',
            3: 'Night',
            4: 'Night',
            5: 'Early Morning',
            6: 'Early Morning',
            7: 'Early Morning',
            8: 'Early Morning',
            9: 'Morning',
            10:'Morning',
            11:'Morning',
            12:'Early Afternoon',
            13:'Early Afternoon',
            14:'Early Afternoon',
            15:'Afternoon',
            16:'Afternoon',
            17:'Afternoon',
            19:'Early Evening',
            20:'Early Evening',
            21:'Evening',
            22:'Evening',
            23:'Evening'}


bna_df['arr_time_blk'] = bna_df['arr_time_blk'].astype(str)
bna_df['arr_time_blk'] = bna_df['arr_time_blk'].str[:2].astype(int)
bna_df['time_of_day'] = bna_df['arr_time_blk'].map(time_map)

In [22]:
# 1 Monday
# 2 Tuesday
# 3 Wednesday
# 4 Thursday
# 5 Friday
# 6 Saturday
# 7 Sunday
# From the bureau of transportation
day_map = {1:'Monday',
           2:'Tuesday',
           3:'Wednesday',
           4:'Thursday',
           5:'Friday',
           6:'Saturday',
           7:'Sunday'}

bna_df['day'] = bna_df['day_of_week'].map(day_map)
bna_df.sample(5)

,year,quarter,month,day_of_month,day_of_week,fl_date,branded_code_share,origin,dest,crs_dep_time,...,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,season,time_of_day,day
500467,2023,3,8,18,5,2023-08-18,WN,BNA,AUS,1630,...,1.0,756.0,NaN,NaN,NaN,NaN,NaN,summer,NaN,Friday
494199,2023,3,8,11,5,2023-08-11,B6,BNA,FLL,1641,...,1.0,793.0,NaN,NaN,NaN,NaN,NaN,summer,Early Evening,Friday
875316,2022,4,12,15,4,2022-12-15,WN,BNA,TPA,2210,...,1.0,612.0,NaN,NaN,NaN,NaN,NaN,winter,Night,Thursday
239133,2024,4,10,5,6,2024-10-05,WN,BNA,PIT,1025,...,1.0,462.0,NaN,NaN,NaN,NaN,NaN,fall,Early Afternoon,Saturday
544577,2023,4,10,9,1,2023-10-09,WN,BNA,MDW,1655,...,1.0,395.0,3.0,0.0,0.0,0.0,17.0,fall,NaN,Monday

#### labeling the weekend or weekend

In [23]:
def week_type(day):
    if day <= 5:
        return 'weekday'
    else:
        return 'weekend'
        
bna_df['week_type'] = bna_df['day_of_week'].map(week_type)
bna_df.sample(5)

,year,quarter,month,day_of_month,day_of_week,fl_date,branded_code_share,origin,dest,crs_dep_time,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,season,time_of_day,day,week_type
400431,2023,2,4,20,4,2023-04-20,WN,BNA,VPS,2010,...,389.0,13.0,0.0,0.0,0.0,76.0,spring,Evening,Thursday,weekday
189002,2024,3,8,9,5,2024-08-09,WN,BNA,MCI,1730,...,491.0,NaN,NaN,NaN,NaN,NaN,summer,Early Evening,Friday,weekday
50154,2024,1,3,7,4,2024-03-07,WN,BNA,DTW,950,...,456.0,NaN,NaN,NaN,NaN,NaN,spring,Early Afternoon,Thursday,weekday
742450,2022,2,6,26,7,2022-06-26,WN,BNA,AUS,805,...,756.0,NaN,NaN,NaN,NaN,NaN,summer,Morning,Sunday,weekend
449937,2023,2,6,19,1,2023-06-19,WN,BNA,PIT,955,...,462.0,NaN,NaN,NaN,NaN,NaN,summer,Early Afternoon,Monday,weekday

# label the airlines

In [24]:
airline_names ={ 'AA': 'American',
                    'AS': 'Alaska',
                    'B6': 'JetBlue', 
                    'DL': 'Delta', 
                    'F9': 'Frontier',
                    'G4': 'Allegiant', 
                    'HA': 'Hawaiian', 
                    'NK': 'Spirit', 
                    'UA': 'United', 
                    'WN': 'Southwest'}
        
bna_df['airline'] = bna_df['branded_code_share'].map(airline_names)
bna_df.sample(5)

,year,quarter,month,day_of_month,day_of_week,fl_date,branded_code_share,origin,dest,crs_dep_time,...,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,season,time_of_day,day,week_type,airline
184334,2024,3,8,4,7,2024-08-04,WN,BNA,RDU,1130,...,NaN,NaN,NaN,NaN,NaN,summer,Early Afternoon,Sunday,weekend,Southwest
485267,2023,3,7,31,1,2023-07-31,WN,BNA,DAL,920,...,NaN,NaN,NaN,NaN,NaN,summer,Morning,Monday,weekday,Southwest
59122,2024,1,3,18,1,2024-03-18,G4,BNA,CID,1816,...,NaN,NaN,NaN,NaN,NaN,spring,Early Evening,Monday,weekday,Allegiant
691101,2022,2,4,20,3,2022-04-20,WN,BNA,AUS,1230,...,0.0,0.0,21.0,0.0,0.0,spring,Early Afternoon,Wednesday,weekday,Southwest
408270,2023,2,4,30,7,2023-04-30,UA,BNA,IAH,602,...,NaN,NaN,NaN,NaN,NaN,spring,Early Morning,Sunday,weekend,United

In [25]:
## We are going to create a seasons list
season_map = {1:"Winter",
              2:"Winter",
              3:"Spring", 
              4:"Spring",
              5:"Spring",
              6:"Summer", 
              7:"Summer", 
              8:"Summer",
              9:"Fall", 
              10:"Fall",
              11:"Fall",
              12:"Winter"}
#The map() function is used to apply a given function to every item of an iterable, such as a list or tuple, and returns a map object (which is an iterator).
#https://www.geeksforgeeks.org/python/python-map-function/
bna_df['season'] = bna_df['month'].map(season_map)
bna_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 237029 entries, 0 to 887175
Data columns (total 32 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 237029 non-null  int64
 1   quarter              237029 non-null  int64
 2   month                237029 non-null  int64
 3   day_of_month         237029 non-null  int64
 4   day_of_week          237029 non-null  int64
 5   fl_date              237029 non-null  object
 6   branded_code_share   237029 non-null  object
 7   origin               237029 non-null  object
 8   dest                 237029 non-null  object
 9   crs_dep_time         237029 non-null  int64
 10  dep_delay_new        233005 non-null  float64
 11  dep_del15            233005 non-null  float64
 12  dep_time_blk         237029 non-null  object
 13  crs_arr_time         237029 non-null  int64
 14  arr_delay_new        232455 non-null  float64
 15  arr_del15            232455 non-null  float64
 16  arr_time_blk         237029 non-null  int32
 17  cancelled            237029 non-null  float64
 18  cancellation_code    4086 non-null    object
 19  diverted             237029 non-null  float64
 20  flights              237029 non-null  float64
 21  distance             237029 non-null  float64
 22  carrier_delay        46696 non-null   float64
 23  weather_delay        46696 non-null   float64
 24  nas_delay            46696 non-null   float64
 25  security_delay       46696 non-null   float64
 26  late_aircraft_delay  46696 non-null   float64
 27  season               237029 non-null  object
 28  time_of_day          223000 non-null  object
 29  day                  237029 non-null  object
 30  week_type            237029 non-null  object
 31  airline              237029 non-null  object
dtypes: float64(13), int32(1), int64(7), object(11)
memory usage: 58.8+ MB

In [26]:
percent_missing = bna_df.isnull().sum() * 100 / len(bna_df)
missing_value_df = pd.DataFrame({'column_name': bna_df.columns,
                                 'percent_missing': percent_missing})
missing_value_df

                             column_name  percent_missing
year                                year         0.000000
quarter                          quarter         0.000000
month                              month         0.000000
day_of_month                day_of_month         0.000000
day_of_week                  day_of_week         0.000000
fl_date                          fl_date         0.000000
branded_code_share    branded_code_share         0.000000
origin                            origin         0.000000
dest                                dest         0.000000
crs_dep_time                crs_dep_time         0.000000
dep_delay_new              dep_delay_new         1.697683
dep_del15                      dep_del15         1.697683
dep_time_blk                dep_time_blk         0.000000
crs_arr_time                crs_arr_time         0.000000
arr_delay_new              arr_delay_new         1.929722
arr_del15                      arr_del15         1.929722
arr_time_blk                arr_time_blk         0.000000
cancelled                      cancelled         0.000000
cancellation_code      cancellation_code        98.276160
diverted                        diverted         0.000000
flights                          flights         0.000000
distance                        distance         0.000000
carrier_delay              carrier_delay        80.299457
weather_delay              weather_delay        80.299457
nas_delay                      nas_delay        80.299457
security_delay            security_delay        80.299457
late_aircraft_delay  late_aircraft_delay        80.299457
season                            season         0.000000
time_of_day                  time_of_day         5.918685
day                                  day         0.000000
week_type                      week_type         0.000000
airline                          airline         0.000000

# THIS IS FOR ARRIVAL ON TIME PERFORMANCE

In [27]:
bna_df['carrier_delay_flight'] = bna_df['carrier_delay'].apply(lambda x: 1 if x > 0 else 0)
bna_df['weather_delay_flight'] = bna_df['weather_delay'].apply(lambda x: 1 if x > 0 else 0)
bna_df['nas_delay_flight'] = bna_df['nas_delay'].apply(lambda x: 1 if x > 0 else 0)
bna_df['security_delay_flight'] = bna_df['security_delay'].apply(lambda x: 1 if x > 0 else 0)
bna_df['late_aircraft_delay_flight'] = bna_df['late_aircraft_delay'].apply(lambda x: 1 if x > 0 else 0)

In [28]:
# Aggregate sums by carrier
carrier_performance_agg = bna_df.groupby('airline')[['flights',
                                                                'arr_del15',
                                                                'arr_delay_new', 
                                                                'dep_del15', 
                                                                'dep_delay_new',
                                                                'cancelled', 
                                                                'diverted', 
                                                                'carrier_delay_flight',
                                                                'weather_delay_flight',
                                                                'nas_delay_flight', 
                                                                'security_delay_flight', 
                                                                'late_aircraft_delay_flight']].sum().reset_index()

#Percentages
carrier_performance_agg['Arrival Flight Delays (%)'] = (
    carrier_performance_agg['arr_del15'] / carrier_performance_agg['flights'] * 100).round(2)

carrier_performance_agg['Departure Flight Delays (%)'] = (
    carrier_performance_agg['dep_del15'] / carrier_performance_agg['flights'] * 100).round(2)

carrier_performance_agg['% cancelled'] = (
    carrier_performance_agg['cancelled'] / carrier_performance_agg['flights'] * 100).round(2)

carrier_performance_agg['% diverted'] = (
    carrier_performance_agg['diverted'] / carrier_performance_agg['flights'] * 100).round(2)

# Step 3: Average delays (handle division by zero)
carrier_performance_agg['Avg. arrival delay (min)'] = np.where(
    carrier_performance_agg['arr_del15'] > 0,
    carrier_performance_agg['arr_delay_new'] / carrier_performance_agg['arr_del15'],0)

carrier_performance_agg['Avg. departure delay (min)'] = np.where(
    carrier_performance_agg['dep_del15'] > 0,
    carrier_performance_agg['dep_delay_new'] / carrier_performance_agg['dep_del15'],0)

#Percent of flights delayed by cause
flights = carrier_performance_agg['flights'] 

carrier_performance_agg['% delayed due to carrier'] = (carrier_performance_agg['carrier_delay_flight'] / 
                                                       flights* 100).round(2)

carrier_performance_agg['% delayed due to weather'] = (carrier_performance_agg['weather_delay_flight'] / 
                                                       flights * 100).round(2)

carrier_performance_agg['% delayed due to NAS'] = (carrier_performance_agg['nas_delay_flight'] / 
                                                   flights * 100).round(2)

carrier_performance_agg['% delayed due to security'] = (carrier_performance_agg['security_delay_flight'] / 
                                                        flights * 100).round(2)

carrier_performance_agg['% delayed due to late aircraft'] = (carrier_performance_agg['late_aircraft_delay_flight'] / 
                                                             flights * 100).round(2)

#Column order
columns_order = ['airline',
                    'flights',
                    'arr_del15',
                    'Arrival Flight Delays (%)',
                    'Avg. arrival delay (min)',
                    'dep_del15',
                    'Departure Flight Delays (%)',
                    'Avg. departure delay (min)',
                    'cancelled',
                    '% cancelled',
                    '% diverted',
                    '% delayed due to carrier',
                    '% delayed due to weather',
                    '% delayed due to NAS',
                    '% delayed due to security',
                    '% delayed due to late aircraft']

carrier_performance_agg = carrier_performance_agg[columns_order]

#Sort by arrival and departure delays
carrier_performance_agg = carrier_performance_agg.sort_values(by=['Arrival Flight Delays (%)', 'Departure Flight Delays (%)'], ascending=[False, False])
carrier_performance_agg

,airline,flights,arr_del15,Arrival Flight Delays (%),Avg. arrival delay (min),dep_del15,Departure Flight Delays (%),Avg. departure delay (min),cancelled,% cancelled,% diverted,% delayed due to carrier,% delayed due to weather,% delayed due to NAS,% delayed due to security,% delayed due to late aircraft
5,JetBlue,5768.0,1779.0,30.84,90.993817,1786.0,30.96,91.855543,195.0,3.38,0.45,20.06,0.64,16.50,0.02,20.80
4,Frontier,2779.0,809.0,29.11,72.391842,758.0,27.28,73.965699,77.0,2.77,0.18,12.27,0.72,18.39,0.00,18.17
7,Spirit,9507.0,2574.0,27.07,77.705128,2600.0,27.35,78.395385,260.0,2.73,0.20,13.88,1.44,20.89,0.25,10.21
1,Allegiant,9560.0,2274.0,23.79,81.223835,2056.0,21.51,83.090953,155.0,1.62,0.26,10.17,2.45,14.87,0.07,12.64
2,American,23785.0,5349.0,22.49,97.874182,4976.0,20.92,102.511656,487.0,2.05,0.25,11.96,1.46,11.69,0.13,12.65
0,Alaska,2740.0,551.0,20.11,56.626134,590.0,21.53,56.169492,38.0,1.39,0.11,7.96,1.72,13.39,0.22,5.80
8,United,16215.0,3227.0,19.90,85.972110,3018.0,18.61,89.023194,303.0,1.87,0.22,10.21,0.80,11.21,0.00,9.37
6,Southwest,142665.0,27357.0,19.18,57.063932,32504.0,22.78,55.969204,2312.0,1.62,0.21,10.86,0.44,7.27,0.03,13.71
3,Delta,24010.0,2776.0,11.56,84.991354,2781.0,11.58,86.865516,259.0,1.08,0.08,4.21,0.79,5.12,0.00,6.25

# time_of day_df

In [29]:
# Aggregate sums by time_of_day
time_of_day_perf = bna_df.groupby('time_of_day')[['flights',
                                                   'arr_del15',
                                                   'arr_delay_new', 
                                                   'dep_del15', 
                                                   'dep_delay_new',
                                                   'cancelled', 
                                                   'diverted', 
                                                   'carrier_delay_flight',
                                                   'weather_delay_flight',
                                                   'nas_delay_flight', 
                                                   'security_delay_flight', 
                                                   'late_aircraft_delay_flight']].sum().reset_index()

# Percentages
time_of_day_perf['Arrival Flight Delays (%)'] = (
    time_of_day_perf['arr_del15'] / time_of_day_perf['flights'] * 100).round(2)

time_of_day_perf['Departure Flight Delays (%)'] = (
    time_of_day_perf['dep_del15'] / time_of_day_perf['flights'] * 100).round(2)

time_of_day_perf['% cancelled'] = (
    time_of_day_perf['cancelled'] / time_of_day_perf['flights'] * 100).round(2)

time_of_day_perf['% diverted'] = (
    time_of_day_perf['diverted'] / time_of_day_perf['flights'] * 100).round(2)

# Average delays (handle division by zero)
time_of_day_perf['Avg. arrival delay (min)'] = np.where(
    time_of_day_perf['arr_del15'] > 0,
    time_of_day_perf['arr_delay_new'] / time_of_day_perf['arr_del15'], 0)

time_of_day_perf['Avg. departure delay (min)'] = np.where(
    time_of_day_perf['dep_del15'] > 0,
    time_of_day_perf['dep_delay_new'] / time_of_day_perf['dep_del15'], 0)

# Percent of flights delayed by cause
flights = time_of_day_perf['flights'] 

time_of_day_perf['% delayed due to carrier'] = (time_of_day_perf['carrier_delay_flight'] / 
                                                flights * 100).round(2)

time_of_day_perf['% delayed due to weather'] = (time_of_day_perf['weather_delay_flight'] / 
                                                flights * 100).round(2)

time_of_day_perf['% delayed due to NAS'] = (time_of_day_perf['nas_delay_flight'] / 
                                            flights * 100).round(2)

time_of_day_perf['% delayed due to security'] = (time_of_day_perf['security_delay_flight'] / 
                                                 flights * 100).round(2)

time_of_day_perf['% delayed due to late aircraft'] = (time_of_day_perf['late_aircraft_delay_flight'] / 
                                                      flights * 100).round(2)

# Column order
columns_order = ['time_of_day',
                 'flights',
                 'arr_del15',
                 'Arrival Flight Delays (%)',
                 'Avg. arrival delay (min)',
                 'dep_del15',
                 'Departure Flight Delays (%)',
                 'Avg. departure delay (min)',
                 'cancelled',
                 '% cancelled',
                 '% diverted',
                 '% delayed due to carrier',
                 '% delayed due to weather',
                 '% delayed due to NAS',
                 '% delayed due to security',
                 '% delayed due to late aircraft']

time_of_day_perf = time_of_day_perf[columns_order]

# Sort by arrival and departure delays
time_of_day_perf = time_of_day_perf.sort_values(by=['Arrival Flight Delays (%)', 'Departure Flight Delays (%)'], 
                                                ascending=[False, False])
time_of_day_perf

,time_of_day,flights,arr_del15,Arrival Flight Delays (%),Avg. arrival delay (min),dep_del15,Departure Flight Delays (%),Avg. departure delay (min),cancelled,% cancelled,% diverted,% delayed due to carrier,% delayed due to weather,% delayed due to NAS,% delayed due to security,% delayed due to late aircraft
6,Night,7515.0,2405.0,32.00,58.967152,3084.0,41.04,58.212711,194.0,2.58,0.11,16.47,0.41,7.08,0.05,27.33
4,Evening,42534.0,12610.0,29.65,66.967090,14783.0,34.76,64.404248,934.0,2.20,0.11,15.62,0.82,10.30,0.04,23.13
2,Early Evening,25735.0,7330.0,28.48,71.358254,8005.0,31.11,69.488195,467.0,1.81,0.27,14.77,1.33,12.99,0.05,20.74
0,Afternoon,36884.0,7737.0,20.98,67.985395,8441.0,22.89,65.868499,532.0,1.44,0.37,11.57,0.96,11.24,0.05,13.53
1,Early Afternoon,41884.0,5718.0,13.65,67.907660,6536.0,15.61,65.343482,555.0,1.33,0.15,7.56,0.49,6.50,0.02,8.28
5,Morning,48390.0,5291.0,10.93,75.301455,4897.0,10.12,80.541760,767.0,1.59,0.16,5.85,0.60,6.37,0.04,2.73
3,Early Morning,20058.0,1714.0,8.55,89.289965,1394.0,6.95,102.406743,378.0,1.88,0.18,5.17,0.28,5.45,0.04,0.53

In [30]:
# Aggregate sums by time_of_day
time_of_day_perf = bna_df.groupby(['time_of_day', 'airline'])[['flights',
                                                   'arr_del15',
                                                   'arr_delay_new', 
                                                   'dep_del15', 
                                                   'dep_delay_new',
                                                   'cancelled', 
                                                   'diverted', 
                                                   'carrier_delay_flight',
                                                   'weather_delay_flight',
                                                   'nas_delay_flight', 
                                                   'security_delay_flight', 
                                                   'late_aircraft_delay_flight']].sum().reset_index()

# Percentages
time_of_day_perf['Arrival Flight Delays (%)'] = (
    time_of_day_perf['arr_del15'] / time_of_day_perf['flights'] * 100).round(2)

time_of_day_perf['Departure Flight Delays (%)'] = (
    time_of_day_perf['dep_del15'] / time_of_day_perf['flights'] * 100).round(2)

time_of_day_perf['% cancelled'] = (
    time_of_day_perf['cancelled'] / time_of_day_perf['flights'] * 100).round(2)

time_of_day_perf['% diverted'] = (
    time_of_day_perf['diverted'] / time_of_day_perf['flights'] * 100).round(2)

# Average delays (handle division by zero)
time_of_day_perf['Avg. arrival delay (min)'] = np.where(
    time_of_day_perf['arr_del15'] > 0,
    time_of_day_perf['arr_delay_new'] / time_of_day_perf['arr_del15'], 0)

time_of_day_perf['Avg. departure delay (min)'] = np.where(
    time_of_day_perf['dep_del15'] > 0,
    time_of_day_perf['dep_delay_new'] / time_of_day_perf['dep_del15'], 0)

# Percent of flights delayed by cause
flights = time_of_day_perf['flights'] 

time_of_day_perf['% delayed due to carrier'] = (time_of_day_perf['carrier_delay_flight'] / 
                                                flights * 100).round(2)

time_of_day_perf['% delayed due to weather'] = (time_of_day_perf['weather_delay_flight'] / 
                                                flights * 100).round(2)

time_of_day_perf['% delayed due to NAS'] = (time_of_day_perf['nas_delay_flight'] / 
                                            flights * 100).round(2)

time_of_day_perf['% delayed due to security'] = (time_of_day_perf['security_delay_flight'] / 
                                                 flights * 100).round(2)

time_of_day_perf['% delayed due to late aircraft'] = (time_of_day_perf['late_aircraft_delay_flight'] / 
                                                      flights * 100).round(2)

# Column order
columns_order = ['time_of_day',
                 'airline',
                 'flights',
                 'arr_del15',
                 'Arrival Flight Delays (%)',
                 'Avg. arrival delay (min)',
                 'dep_del15',
                 'Departure Flight Delays (%)',
                 'Avg. departure delay (min)',
                 'cancelled',
                 '% cancelled',
                 '% diverted',
                 '% delayed due to carrier',
                 '% delayed due to weather',
                 '% delayed due to NAS',
                 '% delayed due to security',
                 '% delayed due to late aircraft']

time_of_day_perf = time_of_day_perf[columns_order]

# Sort by arrival and departure delays
airline_time_of_day_perf = time_of_day_perf.sort_values(by=['Arrival Flight Delays (%)', 'Departure Flight Delays (%)'], 
                                                ascending=[False, False])
airline_time_of_day_perf

,time_of_day,airline,flights,arr_del15,Arrival Flight Delays (%),Avg. arrival delay (min),dep_del15,Departure Flight Delays (%),Avg. departure delay (min),cancelled,% cancelled,% diverted,% delayed due to carrier,% delayed due to weather,% delayed due to NAS,% delayed due to security,% delayed due to late aircraft
53,Night,JetBlue,58.0,30.0,51.72,153.933333,34.0,58.62,150.794118,3.0,5.17,1.72,36.21,0.00,8.62,0.00,44.83
39,Evening,JetBlue,1254.0,532.0,42.42,104.381579,569.0,45.37,102.950791,75.0,5.98,0.24,26.63,0.72,19.78,0.00,36.20
22,Early Evening,JetBlue,762.0,322.0,42.26,97.624224,311.0,40.81,102.508039,20.0,2.62,0.66,26.51,1.31,21.39,0.00,32.68
21,Early Evening,Frontier,483.0,174.0,36.02,73.827586,173.0,35.82,73.294798,14.0,2.90,0.00,17.81,1.04,21.74,0.00,24.22
36,Evening,American,2408.0,863.0,35.84,88.177289,859.0,35.67,90.159488,68.0,2.82,0.12,15.32,1.62,14.70,0.29,30.90
52,Night,Frontier,117.0,41.0,35.04,103.317073,43.0,36.75,114.441860,12.0,10.26,0.00,9.40,0.00,17.09,0.00,30.77
55,Night,Spirit,418.0,145.0,34.69,72.034483,167.0,39.95,75.706587,16.0,3.83,0.00,16.27,0.72,23.44,0.48,19.86
18,Early Evening,Allegiant,1388.0,479.0,34.51,90.814196,448.0,32.28,93.562500,22.0,1.59,0.14,15.78,2.88,20.61,0.07,23.13
35,Evening,Allegiant,1273.0,438.0,34.41,94.609589,436.0,34.25,94.594037,37.0,2.91,0.00,14.45,2.67,17.83,0.16,25.84
19,Early Evening,American,2998.0,1024.0,34.16,93.621094,1027.0,34.26,93.518987,71.0,2.37,0.30,17.38,2.94,16.61,0.17,26.65
24,Early Evening,Spirit,957.0,323.0,33.75,84.523220,331.0,34.59,82.365559,27.0,2.82,0.10,16.72,2.09,27.48,0.10,16.41
3,Afternoon,Frontier,496.0,163.0,32.86,70.435583,140.0,28.23,74.178571,8.0,1.61,0.00,12.30,0.81,22.58,0.00,20.56
38,Evening,Frontier,605.0,194.0,32.07,77.634021,187.0,30.91,74.946524,23.0,3.80,0.33,13.39,0.66,19.67,0.00,22.81
41,Evening,Spirit,1757.0,563.0,32.04,87.531083,613.0,34.89,86.476346,79.0,4.50,0.06,14.74,1.54,24.36,0.23,15.14
54,Night,Southwest,6906.0,2188.0,31.68,55.960238,2839.0,41.11,55.212751,163.0,2.36,0.10,16.46,0.41,5.92,0.03,27.63
4,Afternoon,JetBlue,634.0,193.0,30.44,89.668394,200.0,31.55,86.675000,11.0,1.74,0.79,17.19,0.79,19.72,0.00,17.51
40,Evening,Southwest,29203.0,8670.0,29.69,57.418916,10630.0,36.40,55.505738,538.0,1.84,0.12,16.64,0.54,8.14,0.01,24.19
6,Afternoon,Spirit,1683.0,490.0,29.11,68.767347,469.0,27.87,69.411514,37.0,2.20,0.59,14.14,2.02,24.18,0.24,10.75
23,Early Evening,Southwest,13760.0,3885.0,28.23,58.560103,4568.0,33.20,57.115806,242.0,1.76,0.32,15.97,0.81,10.73,0.04,21.86
25,Early Evening,United,1272.0,353.0,27.75,87.133144,317.0,24.92,90.533123,20.0,1.57,0.24,13.44,1.18,15.17,0.00,14.47
1,Afternoon,American,2805.0,748.0,26.67,94.747326,774.0,27.59,90.702842,44.0,1.57,0.53,15.54,2.46,13.76,0.18,20.43
42,Evening,United,2830.0,749.0,26.47,83.849132,837.0,29.58,80.967742,71.0,2.51,0.14,13.64,1.20,12.30,0.00,16.50
17,Early Evening,Alaska,744.0,196.0,26.34,56.612245,234.0,31.45,54.089744,11.0,1.48,0.13,11.42,1.61,16.80,0.00,11.56
0,Afternoon,Allegiant,2262.0,556.0,24.58,74.030576,523.0,23.12,73.407266,30.0,1.33,0.44,10.65,2.30,15.78,0.00,15.03
32,Early Morning,Spirit,814.0,186.0,22.85,82.575269,206.0,25.31,79.548544,33.0,4.05,0.25,17.57,0.61,15.23,0.49,5.16
13,Early Afternoon,JetBlue,1627.0,359.0,22.07,72.715877,367.0,22.56,69.618529,42.0,2.58,0.37,15.67,0.25,11.99,0.00,15.73
15,Early Afternoon,Spirit,1557.0,343.0,22.03,69.346939,322.0,20.68,71.046584,33.0,2.12,0.26,10.40,1.03,17.73,0.32,7.06
47,Morning,Frontier,161.0,34.0,21.12,73.941176,29.0,18.01,81.206897,2.0,1.24,0.62,6.83,0.62,14.91,0.00,8.70
7,Afternoon,United,3384.0,709.0,20.95,89.493653,647.0,19.12,93.897991,61.0,1.80,0.53,9.90,1.00,13.24,0.00,10.05
12,Early Afternoon,Frontier,474.0,99.0,20.89,60.060606,87.0,18.35,61.678161,9.0,1.90,0.21,8.23,0.42,15.19,0.00,11.81
50,Morning,Spirit,1812.0,368.0,20.31,67.225543,331.0,18.27,72.652568,29.0,1.60,0.00,11.53,1.21,14.18,0.17,3.75
5,Afternoon,Southwest,22349.0,4513.0,20.19,56.152227,5292.0,23.68,54.820673,315.0,1.41,0.34,12.09,0.56,9.65,0.04,13.86
43,Morning,Alaska,1115.0,218.0,19.55,54.651376,181.0,16.23,57.303867,16.0,1.43,0.18,7.00,1.35,14.26,0.45,2.42
34,Evening,Alaska,606.0,118.0,19.47,51.644068,150.0,24.75,52.346667,10.0,1.65,0.00,8.25,2.97,11.06,0.17,7.43
48,Morning,JetBlue,979.0,190.0,19.41,67.973684,155.0,15.83,75.767742,36.0,3.68,0.20,13.59,0.61,11.85,0.10,2.04
37,Evening,Delta,2598.0,483.0,18.59,83.494824,502.0,19.32,83.956175,33.0,1.27,0.04,4.73,0.96,8.20,0.00,12.82
10,Early Afternoon,American,3272.0,560.0,17.11,111.935714,636.0,19.44,103.327044,37.0,1.13,0.24,9.90,1.01,6.75,0.09,12.68
20,Early Evening,Delta,3371.0,574.0,17.03,74.470383,596.0,17.68,74.176174,40.0,1.19,0.12,4.75,1.25,6.91,0.00,12.37
9,Early Afternoon,Allegiant,1659.0,282.0,17.00,68.900709,246.0,14.83,69.715447,19.0,1.15,0.06,6.75,2.29,10.61,0.00,7.41
45,Morning,American,7158.0,1212.0,16.93,102.717822,897.0,12.53,127.484950,160.0,2.24,0.25,9.07,1.09,10.62,0.10,2.14
29,Early Morning,Frontier,246.0,40.0,16.26,56.725000,34.0,13.82,57.382353,7.0,2.85,0.00,10.98,1.63,10.98,0.00,0.00
44,Morning,Allegiant,2084.0,318.0,15.26,74.738994,232.0,11.13,79.857759,31.0,1.49,0.29,6.29,2.35,11.37,0.10,0.48
27,Early Morning,American,3783.0,557.0,14.72,112.298025,385.0,10.18,145.511688,83.0,2.19,0.11,8.93,0.45,9.60,0.03,0.69
30,Early Morning,JetBlue,134.0,19.0,14.18,67.631579,20.0,14.93,55.300000,3.0,2.24,0.75,12.69,0.00,9.70,0.00,0.00
26,Early Morning,Allegiant,473.0,66.0,13.95,60.242424,44.0,9.30,65.454545,7.0,1.48,1.06,5.29,1.69,11.42,0.00,0.21
33,Early Morning,United,916.0,121.0,13.21,85.611570,104.0,11.35,92.250000,8.0,0.87,0.00,7.86,0.55,7.31,0.00,0.66
14,Early Afternoon,Southwest,26206.0,3332.0,12.71,55.338836,4092.0,15.61,54.255621,345.0,1.32,0.15,7.58,0.27,5.62,0.01,7.82
51,Morning,United,4015.0,503.0,12.53,88.200795,503.0,12.53,89.017893,86.0,2.14,0.05,8.39,0.50,6.20,0.00,2.94
16,Early Afternoon,United,2281.0,264.0,11.57,95.352273,245.0,10.74,98.510204,27.0,1.18,0.09,5.92,0.44,6.23,0.00,6.09
2,Afternoon,Delta,3271.0,365.0,11.16,94.854795,396.0,12.11,91.573232,26.0,0.79,0.03,4.46,0.95,4.71,0.00,7.49
11,Early Afternoon,Delta,4533.0,460.0,10.15,84.100000,516.0,11.38,81.430233,42.0,0.93,0.04,3.26,0.64,3.35,0.00,7.04
46,Morning,Delta,5427.0,449.0,8.27,84.975501,393.0,7.24,95.994911,58.0,1.07,0.13,4.22,0.68,4.29,0.00,1.14
49,Morning,Southwest,25639.0,1999.0,7.80,57.807904,2176.0,8.49,59.977482,349.0,1.36,0.16,4.11,0.25,4.09,0.01,3.31
28,Early Morning,Delta,3414.0,251.0,7.35,105.498008,188.0,5.51,128.898936,45.0,1.32,0.03,4.13,0.47,4.42,0.00,0.18
8,Early Afternoon,Alaska,275.0,19.0,6.91,110.368421,25.0,9.09,90.360000,1.0,0.36,0.00,1.82,0.73,5.82,0.00,0.36
56,Night,United,16.0,1.0,6.25,76.000000,1.0,6.25,88.000000,0.0,0.00,0.00,6.25,0.00,0.00,0.00,6.25
31,Early Morning,Southwest,10278.0,474.0,4.61,64.905063,413.0,4.02,74.048426,192.0,1.87,0.23,2.66,0.02,2.86,0.03,0.24

# day of the week

In [31]:
# groupby day and sum the columns
day_perf = bna_df.groupby('day')[['flights',
                                  'arr_del15',
                                  'arr_delay_new', 
                                  'dep_del15', 
                                  'dep_delay_new',
                                  'cancelled', 
                                  'diverted', 
                                  'carrier_delay_flight',
                                  'weather_delay_flight',
                                  'nas_delay_flight', 
                                  'security_delay_flight', 
                                  'late_aircraft_delay_flight']].sum().reset_index()

# Percentages
day_perf['Arrival Flight Delays (%)'] = (day_perf['arr_del15'] / day_perf['flights'] * 100).round(2)
day_perf['Departure Flight Delays (%)'] = (day_perf['dep_del15'] / day_perf['flights'] * 100).round(2)
day_perf['% cancelled'] = (day_perf['cancelled'] / day_perf['flights'] * 100).round(2)
day_perf['% diverted'] = (day_perf['diverted'] / day_perf['flights'] * 100).round(2)

# Average delays (handle division by zero)
day_perf['Avg. arrival delay (min)'] = np.where(day_perf['arr_del15'] > 0,
                                                day_perf['arr_delay_new'] / day_perf['arr_del15'], 0)
day_perf['Avg. departure delay (min)'] = np.where(day_perf['dep_del15'] > 0,
                                                  day_perf['dep_delay_new'] / day_perf['dep_del15'], 0)

# Percent of flights delayed by cause
flights = day_perf['flights']
day_perf['% delayed due to carrier'] = (day_perf['carrier_delay_flight'] / flights * 100).round(2)
day_perf['% delayed due to weather'] = (day_perf['weather_delay_flight'] / flights * 100).round(2)
day_perf['% delayed due to NAS'] = (day_perf['nas_delay_flight'] / flights * 100).round(2)
day_perf['% delayed due to security'] = (day_perf['security_delay_flight'] / flights * 100).round(2)
day_perf['% delayed due to late aircraft'] = (day_perf['late_aircraft_delay_flight'] / flights * 100).round(2)

# Column order
columns_order = ['day',
                 'flights',
                 'arr_del15',
                 'Arrival Flight Delays (%)',
                 'Avg. arrival delay (min)',
                 'dep_del15',
                 'Departure Flight Delays (%)',
                 'Avg. departure delay (min)',
                 'cancelled',
                 '% cancelled',
                 '% diverted',
                 '% delayed due to carrier',
                 '% delayed due to weather',
                 '% delayed due to NAS',
                 '% delayed due to security',
                 '% delayed due to late aircraft']

day_perf = day_perf[columns_order]

# Sorted by arrival and departure delays
day_perf = day_perf.sort_values(by=['Arrival Flight Delays (%)', 'Departure Flight Delays (%)'], ascending=[False, False])
day_perf

,day,flights,arr_del15,Arrival Flight Delays (%),Avg. arrival delay (min),dep_del15,Departure Flight Delays (%),Avg. departure delay (min),cancelled,% cancelled,% diverted,% delayed due to carrier,% delayed due to weather,% delayed due to NAS,% delayed due to security,% delayed due to late aircraft
0,Friday,35616.0,7940.0,22.29,69.138917,8620.0,24.20,67.768910,661.0,1.86,0.18,11.95,0.81,10.49,0.06,14.64
3,Sunday,35957.0,7938.0,22.08,69.749559,8714.0,24.23,68.388111,587.0,1.63,0.21,12.66,0.85,10.10,0.10,14.46
4,Thursday,34989.0,7194.0,20.56,66.672505,7841.0,22.41,65.582961,717.0,2.05,0.19,10.74,0.66,9.56,0.03,13.36
2,Saturday,29517.0,5883.0,19.93,68.385518,6486.0,21.97,66.594820,422.0,1.43,0.26,11.06,0.74,8.98,0.03,11.92
1,Monday,35674.0,6786.0,19.02,72.817713,7379.0,20.68,71.115463,616.0,1.73,0.21,10.28,0.77,8.80,0.04,11.71
6,Wednesday,32802.0,5636.0,17.18,70.596700,6170.0,18.81,69.449433,582.0,1.77,0.22,8.58,0.62,7.89,0.03,10.85
5,Tuesday,32474.0,5319.0,16.38,67.257379,5859.0,18.04,66.214883,501.0,1.54,0.18,8.31,0.76,7.22,0.02,10.16

# season_df

In [32]:
# Group by season and sum 
season_perf = bna_df.groupby('season')[['flights',
                                        'arr_del15',
                                        'arr_delay_new', 
                                        'dep_del15', 
                                        'dep_delay_new',
                                        'cancelled', 
                                        'diverted', 
                                        'carrier_delay_flight',
                                        'weather_delay_flight',
                                        'nas_delay_flight', 
                                        'security_delay_flight', 
                                        'late_aircraft_delay_flight']].sum().reset_index()

# Percentages
season_perf['Arrival Flight Delays (%)'] = (season_perf['arr_del15'] / season_perf['flights'] * 100).round(2)
season_perf['Departure Flight Delays (%)'] = (season_perf['dep_del15'] / season_perf['flights'] * 100).round(2)
season_perf['% cancelled'] = (season_perf['cancelled'] / season_perf['flights'] * 100).round(2)
season_perf['% diverted'] = (season_perf['diverted'] / season_perf['flights'] * 100).round(2)

# Average delays
season_perf['Avg. arrival delay (min)'] = np.where(season_perf['arr_del15'] > 0,
                                                  season_perf['arr_delay_new'] / season_perf['arr_del15'], 0)
season_perf['Avg. departure delay (min)'] = np.where(season_perf['dep_del15'] > 0,
                                                    season_perf['dep_delay_new'] / season_perf['dep_del15'], 0)

# Percent of flights delayed by cause
flights = season_perf['flights']
season_perf['% delayed due to carrier'] = (season_perf['carrier_delay_flight'] / flights * 100).round(2)
season_perf['% delayed due to weather'] = (season_perf['weather_delay_flight'] / flights * 100).round(2)
season_perf['% delayed due to NAS'] = (season_perf['nas_delay_flight'] / flights * 100).round(2)
season_perf['% delayed due to security'] = (season_perf['security_delay_flight'] / flights * 100).round(2)
season_perf['% delayed due to late aircraft'] = (season_perf['late_aircraft_delay_flight'] / flights * 100).round(2)

# Column order
columns_order = ['season',
                 'flights',
                 'arr_del15',
                 'Arrival Flight Delays (%)',
                 'Avg. arrival delay (min)',
                 'dep_del15',
                 'Departure Flight Delays (%)',
                 'Avg. departure delay (min)',
                 'cancelled',
                 '% cancelled',
                 '% diverted',
                 '% delayed due to carrier',
                 '% delayed due to weather',
                 '% delayed due to NAS',
                 '% delayed due to security',
                 '% delayed due to late aircraft']

season_perf = season_perf[columns_order]

# Sort by arrival and departure delays
season_perf = season_perf.sort_values(by=['Arrival Flight Delays (%)', 'Departure Flight Delays (%)'], ascending=[False, False])
season_perf

,season,flights,arr_del15,Arrival Flight Delays (%),Avg. arrival delay (min),dep_del15,Departure Flight Delays (%),Avg. departure delay (min),cancelled,% cancelled,% diverted,% delayed due to carrier,% delayed due to weather,% delayed due to NAS,% delayed due to security,% delayed due to late aircraft
2,Summer,62068.0,15096.0,24.32,70.918058,16476.0,26.55,69.411326,942.0,1.52,0.30,13.04,0.99,10.57,0.05,16.55
1,Spring,58224.0,12493.0,21.46,69.810694,13497.0,23.18,68.389198,704.0,1.21,0.24,11.36,0.74,10.15,0.08,13.66
3,Winter,54105.0,9832.0,18.17,71.951587,10612.0,19.61,70.136261,2038.0,3.77,0.12,9.64,0.98,8.90,0.04,10.66
0,Fall,62632.0,9275.0,14.81,62.986846,10484.0,16.74,62.622377,402.0,0.64,0.15,8.12,0.31,6.63,0.02,9.01

# week_type df

In [33]:
# Group by weektype and sum
weektype_perf = bna_df.groupby('week_type')[['flights',
                                            'arr_del15',
                                            'arr_delay_new', 
                                            'dep_del15', 
                                            'dep_delay_new',
                                            'cancelled', 
                                            'diverted', 
                                            'carrier_delay_flight',
                                            'weather_delay_flight',
                                            'nas_delay_flight', 
                                            'security_delay_flight', 
                                            'late_aircraft_delay_flight']].sum().reset_index()

# Percentages
weektype_perf['Arrival Flight Delays (%)'] = (weektype_perf['arr_del15'] / weektype_perf['flights'] * 100).round(2)
weektype_perf['Departure Flight Delays (%)'] = (weektype_perf['dep_del15'] / weektype_perf['flights'] * 100).round(2)
weektype_perf['% cancelled'] = (weektype_perf['cancelled'] / weektype_perf['flights'] * 100).round(2)
weektype_perf['% diverted'] = (weektype_perf['diverted'] / weektype_perf['flights'] * 100).round(2)

# Average delays
weektype_perf['Avg. arrival delay (min)'] = np.where(weektype_perf['arr_del15'] > 0,
                                                     weektype_perf['arr_delay_new'] / weektype_perf['arr_del15'], 0)
weektype_perf['Avg. departure delay (min)'] = np.where(weektype_perf['dep_del15'] > 0,
                                                       weektype_perf['dep_delay_new'] / weektype_perf['dep_del15'], 0)

# Percent of flights delayed by cause
flights = weektype_perf['flights']
weektype_perf['% delayed due to carrier'] = (weektype_perf['carrier_delay_flight'] / flights * 100).round(2)
weektype_perf['% delayed due to weather'] = (weektype_perf['weather_delay_flight'] / flights * 100).round(2)
weektype_perf['% delayed due to NAS'] = (weektype_perf['nas_delay_flight'] / flights * 100).round(2)
weektype_perf['% delayed due to security'] = (weektype_perf['security_delay_flight'] / flights * 100).round(2)
weektype_perf['% delayed due to late aircraft'] = (weektype_perf['late_aircraft_delay_flight'] / flights * 100).round(2)

# Column order
columns_order = ['week_type',
                 'flights',
                 'arr_del15',
                 'Arrival Flight Delays (%)',
                 'Avg. arrival delay (min)',
                 'dep_del15',
                 'Departure Flight Delays (%)',
                 'Avg. departure delay (min)',
                 'cancelled',
                 '% cancelled',
                 '% diverted',
                 '% delayed due to carrier',
                 '% delayed due to weather',
                 '% delayed due to NAS',
                 '% delayed due to security',
                 '% delayed due to late aircraft']

weektype_perf = weektype_perf[columns_order]

# Sort by arrival and departure delays
weektype_perf = weektype_perf.sort_values(by=['Arrival Flight Delays (%)', 'Departure Flight Delays (%)'], ascending=[False, False])
weektype_perf

,week_type,flights,arr_del15,Arrival Flight Delays (%),Avg. arrival delay (min),dep_del15,Departure Flight Delays (%),Avg. departure delay (min),cancelled,% cancelled,% diverted,% delayed due to carrier,% delayed due to weather,% delayed due to NAS,% delayed due to security,% delayed due to late aircraft
1,weekend,65474.0,13821.0,21.11,69.168946,15200.0,23.22,67.622895,1009.0,1.54,0.23,11.94,0.80,9.59,0.07,13.31
0,weekday,171555.0,32875.0,19.16,69.304061,35869.0,20.91,68.014748,3077.0,1.79,0.20,10.02,0.73,8.83,0.03,12.19

In [34]:
bna_df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date',
       'branded_code_share', 'origin', 'dest', 'crs_dep_time', 'dep_delay_new',
       'dep_del15', 'dep_time_blk', 'crs_arr_time', 'arr_delay_new',
       'arr_del15', 'arr_time_blk', 'cancelled', 'cancellation_code',
       'diverted', 'flights', 'distance', 'carrier_delay', 'weather_delay',
       'nas_delay', 'security_delay', 'late_aircraft_delay', 'season',
       'time_of_day', 'day', 'week_type', 'airline', 'carrier_delay_flight',
       'weather_delay_flight', 'nas_delay_flight', 'security_delay_flight',
       'late_aircraft_delay_flight'],
      dtype='object')>

# Download DF

In [35]:
bna_df.to_csv('D:/Jai - NSS/bna-airline-delay-patterns.csv', header=True, index=False)